//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AHC.CD.Entities.DatabaseDesign
{
    using System;
    using System.Collections.Generic;
    
    public partial class HospitalContactInfo
    {
        public HospitalContactInfo()
        {
            this.HospitalContactPersons = new HashSet<HospitalContactPerson>();
        }
    
        public int Id { get; set; }
        public string LocationName { get; set; }
        public string Number { get; set; }
        public string SuiteOrBuilding { get; set; }
        public string Street { get; set; }
        public string County { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string ZipCode { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Status { get; set; }
        public System.DateTime LastUpdatedOn { get; set; }
    
        public virtual ICollection<HospitalContactPerson> HospitalContactPersons { get; set; }
        public virtual HospitalPrivilege HospitalPrivilege { get; set; }
    }
}
