[
    {
        "ServiceSubjectToNotice": "DURABLE MEDICAL EQUIPMENT",
        "ListOfMedicalService": ["SAMPLE LIST 1", "SAMPLE LIST 2"],
        "Rationale": "WE DENIED THIS ITEM LISTED ABOVE BECAUSE: SHOWER CHAIR W/WO WHEELS ANY SIZE (HCPCS CODE E2040) IS NON-COVERED BY MEDICARE.HEREFORE THE REQUESTED SHOWER CHAIR IS DENIED.",
        "CriteriaUsed": "THE DURABLE MEDICAL EQUIPMENT PROSTHETIC ORTHOTICS SERVICES (DMEPOS) PROVIDES A YEARLY UPDATED LIST OF THE HEALTH COMMON PROCEDURE CODING SYSTEM CODES (HCPCS) THAT INCLUDES A LIST OF CODES",
        "AlternaltePlanOfCare": "MEMBER MAY PURCHASE ON HIS/HER OWN.",
        "Note": "Sample Note",
        "ReviewType": "NURSE REVIEW",
        "Decision": "Denial"
    },
    {
        "ServiceSubjectToNotice": "DURABLE MEDICAL EQUIPMENT",
        "ListOfMedicalService": ["SAMPLE LIST 1", "SAMPLE LIST 2"],
        "Rationale": "THE DOCUMENT SUBMITTED IS INSUFFICENT TO SUPPORT THE MEDICARE CRITERIA OF MEDICAL NECESSITY FOR A POWER MOBILITY ASSISTIVE DEVICE, MORE SPECIFICALLY BECAUSE YOU DO NOT HAVE A DOCUMENTED MOBILITY LIMIT",
        "CriteriaUsed": "SAMPLE PLAN",
        "AlternaltePlanOfCare": "",
        "Note": "Sample Note",
        "ReviewType": "NURSE REVIEW",
        "Decision": "Denial"
    },
    {
        "ServiceSubjectToNotice": "DURABLE MEDICAL EQUIPMENT",
        "ListOfMedicalService": ["SAMPLE LIST 1", "SAMPLE LIST 2"],
        "Rationale": "THESE ARE THE RULES THAT APPY TO THE ITEM THAT YOU REQUESTED MEDICARE STATES THAT THE HEALTH PLAN MUST FOLLOW MEDICARE RULES, AND COVER ITEMS IN ACCORDANCE WITH MEDICARE RULES. THEREFORE, YOUR HEALTH",
        "CriteriaUsed": "THE DURABLE MEDICAL EQUIPMENT PROSTHETIC ORTHOTICS SERVICES (DMEPOS) PROVIDES A YEARLY UPDATED LIST OF THE HEALTH COMMON PROCEDURE CODING SYSTEM CODES (HCPCS) THAT INCLUDES A LIST OF CODES ",
        "AlternaltePlanOfCare": "MEMBER MAY PURCHASE ON HIS/HER OWN.",
        "Note": "Sample Note",
        "ReviewType": "MD REVIEW",
        "Decision": "Denial"
    },
    {
        "ServiceSubjectToNotice": "",
        "ListOfMedicalService": [""],
        "Rationale": "",
        "CriteriaUsed": "THE DURABLE MEDICAL EQUIPMENT PROSTHETIC ORTHOTICS SERVICES (DMEPOS) PROVIDES A YEARLY UPDATED LIST OF THE HEALTH COMMON PROCEDURE CODING SYSTEM CODES (HCPCS) THAT INCLUDES A LIST OF CODES ",
        "AlternaltePlanOfCare": "",
        "Note": "Sample Note",
        "ReviewType": "MD REVIEW",
        "Decision": "APPROVAL"
    }
]