//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AHC.CD.Entities.DatabaseDesign
{
    using System;
    using System.Collections.Generic;
    
    public partial class StateLicense
    {
        public int Id { get; set; }
        public string Number { get; set; }
        public string IssueState { get; set; }
        public string PracticeState { get; set; }
        public System.DateTime OriginalIssueDate { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public System.DateTime CurrentIssueDate { get; set; }
        public bool IsInGoodStanding { get; set; }
        public bool IsRelinquished { get; set; }
        public System.DateTime Date { get; set; }
        public System.DateTime RelinquishedDate { get; set; }
        public string CertificatePath { get; set; }
        public string Status { get; set; }
        public System.DateTime LastUpdatedOn { get; set; }
    
        public virtual StateLicenseType StateLicenseType { get; set; }
        public virtual StateLicenceStatus StateLicenceStatus { get; set; }
    }
}
