//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalTemplate.Areas.Portal.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Content {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Content() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PortalTemplate.Areas.Portal.App_LocalResources.Content", typeof(Content).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Member ID.
        /// </summary>
        public static string AccessMemberID {
            get {
                return ResourceManager.GetString("AccessMemberID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD 1.
        /// </summary>
        public static string Add1ICE {
            get {
                return ResourceManager.GetString("Add1ICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD 1.
        /// </summary>
        public static string Add1Representative {
            get {
                return ResourceManager.GetString("Add1Representative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD 2.
        /// </summary>
        public static string Add2ICE {
            get {
                return ResourceManager.GetString("Add2ICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD 2.
        /// </summary>
        public static string Add2Representative {
            get {
                return ResourceManager.GetString("Add2Representative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADDRESS INFORMATION .
        /// </summary>
        public static string AddressInformationICE {
            get {
                return ResourceManager.GetString("AddressInformationICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADDRESS INFORMATION.
        /// </summary>
        public static string AddressInformationRepresentative {
            get {
                return ResourceManager.GetString("AddressInformationRepresentative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADDRESS.
        /// </summary>
        public static string AddressLine1 {
            get {
                return ResourceManager.GetString("AddressLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADDRESS.
        /// </summary>
        public static string AddressMBRProvider {
            get {
                return ResourceManager.GetString("AddressMBRProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADDRESS.
        /// </summary>
        public static string AddressMemberAddress {
            get {
                return ResourceManager.GetString("AddressMemberAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADDRESS.
        /// </summary>
        public static string AddressTitleEnrollment {
            get {
                return ResourceManager.GetString("AddressTitleEnrollment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AGE.
        /// </summary>
        public static string AgeHeader {
            get {
                return ResourceManager.GetString("AgeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CELL.
        /// </summary>
        public static string AlternateContact {
            get {
                return ResourceManager.GetString("AlternateContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTERNATE PHONE.
        /// </summary>
        public static string AlternatePhoneDemoGraphics {
            get {
                return ResourceManager.GetString("AlternatePhoneDemoGraphics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AMOUNT.
        /// </summary>
        public static string AmountOveride {
            get {
                return ResourceManager.GetString("AmountOveride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APPLICANT TYPE.
        /// </summary>
        public static string ApplicantTypeEnrollment {
            get {
                return ResourceManager.GetString("ApplicantTypeEnrollment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BASIC DETAILS.
        /// </summary>
        public static string BasicDetailsTitleEnrollment {
            get {
                return ResourceManager.GetString("BasicDetailsTitleEnrollment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BIRTH DATE.
        /// </summary>
        public static string BirthDateEnrollment {
            get {
                return ResourceManager.GetString("BirthDateEnrollment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CARRIER.
        /// </summary>
        public static string Carrier {
            get {
                return ResourceManager.GetString("Carrier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CATEGORY.
        /// </summary>
        public static string CategoryEligibility {
            get {
                return ResourceManager.GetString("CategoryEligibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CELL.
        /// </summary>
        public static string CellICE {
            get {
                return ResourceManager.GetString("CellICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CELL PHONE.
        /// </summary>
        public static string CellPhoneEnrollment {
            get {
                return ResourceManager.GetString("CellPhoneEnrollment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CELL.
        /// </summary>
        public static string CellRepresentative {
            get {
                return ResourceManager.GetString("CellRepresentative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CENTER NO.
        /// </summary>
        public static string CenterNoMBRProvider {
            get {
                return ResourceManager.GetString("CenterNoMBRProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CITY.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CITY.
        /// </summary>
        public static string CityICE {
            get {
                return ResourceManager.GetString("CityICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CITY.
        /// </summary>
        public static string CityMemberAddress {
            get {
                return ResourceManager.GetString("CityMemberAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CITY.
        /// </summary>
        public static string CityRepresentative {
            get {
                return ResourceManager.GetString("CityRepresentative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CODE.
        /// </summary>
        public static string CodeScreening {
            get {
                return ResourceManager.GetString("CodeScreening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMMENTS.
        /// </summary>
        public static string CommentScreening {
            get {
                return ResourceManager.GetString("CommentScreening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONF.COMM.
        /// </summary>
        public static string ConfCommunicationEnrollment {
            get {
                return ResourceManager.GetString("ConfCommunicationEnrollment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTACT ALERT.
        /// </summary>
        public static string ContactAlertDemoGraphics {
            get {
                return ResourceManager.GetString("ContactAlertDemoGraphics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTACT INFORMATION.
        /// </summary>
        public static string ContactinformationICE {
            get {
                return ResourceManager.GetString("ContactinformationICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTACT INFORMATION.
        /// </summary>
        public static string ContactinformationRepresentative {
            get {
                return ResourceManager.GetString("ContactinformationRepresentative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTACT PREF.
        /// </summary>
        public static string ContactPreferencePhoneDemoGraphics {
            get {
                return ResourceManager.GetString("ContactPreferencePhoneDemoGraphics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTACT.
        /// </summary>
        public static string ContactTitleDemoGraphics {
            get {
                return ResourceManager.GetString("ContactTitleDemoGraphics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COUNTY.
        /// </summary>
        public static string CountyICE {
            get {
                return ResourceManager.GetString("CountyICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COUNTY.
        /// </summary>
        public static string CountyMedicare {
            get {
                return ResourceManager.GetString("CountyMedicare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COUNTY.
        /// </summary>
        public static string CountyRepresentative {
            get {
                return ResourceManager.GetString("CountyRepresentative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CULTURAL/ETHNICITY CHARACTERISTICS.
        /// </summary>
        public static string CultureTitleDemoGraphics {
            get {
                return ResourceManager.GetString("CultureTitleDemoGraphics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOB.
        /// </summary>
        public static string DateOfBirthHeader {
            get {
                return ResourceManager.GetString("DateOfBirthHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DO NOT CALL.
        /// </summary>
        public static string DoNotCallPhoneDemoGraphics {
            get {
                return ResourceManager.GetString("DoNotCallPhoneDemoGraphics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EFF DATE.
        /// </summary>
        public static string EffDateEnrollment {
            get {
                return ResourceManager.GetString("EffDateEnrollment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EFF DATE.
        /// </summary>
        public static string EffDateHeader {
            get {
                return ResourceManager.GetString("EffDateHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EFFECTIVE.
        /// </summary>
        public static string Effective {
            get {
                return ResourceManager.GetString("Effective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EFF DATE.
        /// </summary>
        public static string EffectiveDateEligibility {
            get {
                return ResourceManager.GetString("EffectiveDateEligibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EFFECTIVE.
        /// </summary>
        public static string EffectiveDateMedicare {
            get {
                return ResourceManager.GetString("EffectiveDateMedicare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EFF DATE.
        /// </summary>
        public static string EffectiveDateOveride {
            get {
                return ResourceManager.GetString("EffectiveDateOveride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EFF FROM.
        /// </summary>
        public static string EffectiveFromMBRProvider {
            get {
                return ResourceManager.GetString("EffectiveFromMBRProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EFF TO.
        /// </summary>
        public static string EffectiveToMBRProvider {
            get {
                return ResourceManager.GetString("EffectiveToMBRProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ELIGIBILITY DATE.
        /// </summary>
        public static string EligibilityDateEnrollment {
            get {
                return ResourceManager.GetString("EligibilityDateEnrollment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ELIG.
        /// </summary>
        public static string EligibilityDateHeader {
            get {
                return ResourceManager.GetString("EligibilityDateHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMAIL.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMAIL.
        /// </summary>
        public static string EmailDemoGraphics {
            get {
                return ResourceManager.GetString("EmailDemoGraphics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMAIL.
        /// </summary>
        public static string EmailICE {
            get {
                return ResourceManager.GetString("EmailICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMAIL.
        /// </summary>
        public static string EmailRepresentative {
            get {
                return ResourceManager.GetString("EmailRepresentative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EOI TERMINATION DATE.
        /// </summary>
        public static string EOITerminationDateEnrollment {
            get {
                return ResourceManager.GetString("EOITerminationDateEnrollment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ETHNICITY.
        /// </summary>
        public static string EthinicityDemoGraphics {
            get {
                return ResourceManager.GetString("EthinicityDemoGraphics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EVENT.
        /// </summary>
        public static string EventEligibility {
            get {
                return ResourceManager.GetString("EventEligibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EVENT.
        /// </summary>
        public static string EventMedicare {
            get {
                return ResourceManager.GetString("EventMedicare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXCLUSIONARY PERIOD CREDIT DAYS.
        /// </summary>
        public static string ExclusionaryPeriodCreditDaysEnrollment {
            get {
                return ResourceManager.GetString("ExclusionaryPeriodCreditDaysEnrollment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXPLANATION.
        /// </summary>
        public static string ExplanationEligibility {
            get {
                return ResourceManager.GetString("ExplanationEligibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FACTORS.
        /// </summary>
        public static string FactorsOveride {
            get {
                return ResourceManager.GetString("FactorsOveride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAMILY LINK ID.
        /// </summary>
        public static string FamilylinkIDEnrollment {
            get {
                return ResourceManager.GetString("FamilylinkIDEnrollment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAMILY STATUS.
        /// </summary>
        public static string FamilyStatusDemoGraphics {
            get {
                return ResourceManager.GetString("FamilyStatusDemoGraphics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAX.
        /// </summary>
        public static string FaxMemberAddress {
            get {
                return ResourceManager.GetString("FaxMemberAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIRST NAME.
        /// </summary>
        public static string FirstNameICE {
            get {
                return ResourceManager.GetString("FirstNameICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIRST NAME.
        /// </summary>
        public static string FirstNameRepresentative {
            get {
                return ResourceManager.GetString("FirstNameRepresentative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FROM.
        /// </summary>
        public static string FromDateMedicare {
            get {
                return ResourceManager.GetString("FromDateMedicare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GENDER.
        /// </summary>
        public static string GenderEnrollment {
            get {
                return ResourceManager.GetString("GenderEnrollment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GENDER.
        /// </summary>
        public static string GenderHeader {
            get {
                return ResourceManager.GetString("GenderHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GUARANTOR TYPE.
        /// </summary>
        public static string GuarantorTypeICE {
            get {
                return ResourceManager.GetString("GuarantorTypeICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GUARANTOR TYPE.
        /// </summary>
        public static string GuarantorTypeRepresentative {
            get {
                return ResourceManager.GetString("GuarantorTypeRepresentative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HICN.
        /// </summary>
        public static string HICN {
            get {
                return ResourceManager.GetString("HICN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HICN.
        /// </summary>
        public static string HICNMedicare {
            get {
                return ResourceManager.GetString("HICNMedicare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HIPAA END DATE.
        /// </summary>
        public static string HipaaEndDateEnrollment {
            get {
                return ResourceManager.GetString("HipaaEndDateEnrollment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HIPAA START DATE.
        /// </summary>
        public static string HipaaStartDateEnrollment {
            get {
                return ResourceManager.GetString("HipaaStartDateEnrollment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HIPPA.
        /// </summary>
        public static string HipaaTitleEnrollment {
            get {
                return ResourceManager.GetString("HipaaTitleEnrollment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HISTORY LINK ID.
        /// </summary>
        public static string HistoryLinkIDEnrollment {
            get {
                return ResourceManager.GetString("HistoryLinkIDEnrollment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOME.
        /// </summary>
        public static string HomeAddressEnrollment {
            get {
                return ResourceManager.GetString("HomeAddressEnrollment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOME PHONE.
        /// </summary>
        public static string HomePhoneDemoGraphics {
            get {
                return ResourceManager.GetString("HomePhoneDemoGraphics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TYPE.
        /// </summary>
        public static string IdentificationTypeOveride {
            get {
                return ResourceManager.GetString("IdentificationTypeOveride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INPUT.
        /// </summary>
        public static string InputMedicare {
            get {
                return ResourceManager.GetString("InputMedicare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSURANCE TYPE.
        /// </summary>
        public static string InsuranceType {
            get {
                return ResourceManager.GetString("InsuranceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ELIG.
        /// </summary>
        public static string IsEligibleHeader {
            get {
                return ResourceManager.GetString("IsEligibleHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PCP.
        /// </summary>
        public static string IsPcpMBRProvider {
            get {
                return ResourceManager.GetString("IsPcpMBRProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LANGUAGE.
        /// </summary>
        public static string LanguageEnrollment {
            get {
                return ResourceManager.GetString("LanguageEnrollment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LANGUAGE.
        /// </summary>
        public static string LanguageTitleDemoGraphics {
            get {
                return ResourceManager.GetString("LanguageTitleDemoGraphics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LAST NAME.
        /// </summary>
        public static string LastNameICE {
            get {
                return ResourceManager.GetString("LastNameICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LAST NAME.
        /// </summary>
        public static string LastNameRepresentative {
            get {
                return ResourceManager.GetString("LastNameRepresentative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LAST.
        /// </summary>
        public static string LastScreening {
            get {
                return ResourceManager.GetString("LastScreening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LIMITS.
        /// </summary>
        public static string LimitsEnrollment {
            get {
                return ResourceManager.GetString("LimitsEnrollment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAILING.
        /// </summary>
        public static string MailingAddressEnrollment {
            get {
                return ResourceManager.GetString("MailingAddressEnrollment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MARITAL STATUS.
        /// </summary>
        public static string MaritalStatusDemoGraphics {
            get {
                return ResourceManager.GetString("MaritalStatusDemoGraphics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MARITAL STATUS.
        /// </summary>
        public static string MaritalStatusEnrollment {
            get {
                return ResourceManager.GetString("MaritalStatusEnrollment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COUNTY.
        /// </summary>
        public static string MBRCountyHeader {
            get {
                return ResourceManager.GetString("MBRCountyHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHONE.
        /// </summary>
        public static string MBRPHONEHeader {
            get {
                return ResourceManager.GetString("MBRPHONEHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medicaid.
        /// </summary>
        public static string Medicaid {
            get {
                return ResourceManager.GetString("Medicaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MEDICARE NO.
        /// </summary>
        public static string MedicareNumberEnrollment {
            get {
                return ResourceManager.GetString("MedicareNumberEnrollment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EFF.
        /// </summary>
        public static string MemberEffectiveDate {
            get {
                return ResourceManager.GetString("MemberEffectiveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member ID.
        /// </summary>
        public static string MemberID {
            get {
                return ResourceManager.GetString("MemberID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MEMBER ID.
        /// </summary>
        public static string MemberIDICE {
            get {
                return ResourceManager.GetString("MemberIDICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MEMBER ID.
        /// </summary>
        public static string MemberIDRepresentative {
            get {
                return ResourceManager.GetString("MemberIDRepresentative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MEMBER INFORMATION.
        /// </summary>
        public static string MemberInformationTitle {
            get {
                return ResourceManager.GetString("MemberInformationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MEMBER NAME.
        /// </summary>
        public static string MemberNameEnrollment {
            get {
                return ResourceManager.GetString("MemberNameEnrollment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MBR NAME.
        /// </summary>
        public static string MemberNameHeader {
            get {
                return ResourceManager.GetString("MemberNameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MEMO.
        /// </summary>
        public static string MemoEnrollment {
            get {
                return ResourceManager.GetString("MemoEnrollment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEW SIGNATURE DATE.
        /// </summary>
        public static string NewSignatureDateEnrollment {
            get {
                return ResourceManager.GetString("NewSignatureDateEnrollment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEXT.
        /// </summary>
        public static string NextScreening {
            get {
                return ResourceManager.GetString("NextScreening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NPI.
        /// </summary>
        public static string NPIMBRProvider {
            get {
                return ResourceManager.GetString("NPIMBRProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ORDER.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PARENTAL CONSENT FROM.
        /// </summary>
        public static string ParentalConsentFromPhoneDemoGraphics {
            get {
                return ResourceManager.GetString("ParentalConsentFromPhoneDemoGraphics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PARENTAL CONSENT THRU.
        /// </summary>
        public static string ParentalConsentThruPhoneDemoGraphics {
            get {
                return ResourceManager.GetString("ParentalConsentThruPhoneDemoGraphics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PBP ID.
        /// </summary>
        public static string PBPIDMedicare {
            get {
                return ResourceManager.GetString("PBPIDMedicare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PCP.
        /// </summary>
        public static string PCPNAMEHeader {
            get {
                return ResourceManager.GetString("PCPNAMEHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PCP PHONE.
        /// </summary>
        public static string PCPPHONEHeader {
            get {
                return ResourceManager.GetString("PCPPHONEHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PERSONAL INFORMATION.
        /// </summary>
        public static string PersonalInformationICE {
            get {
                return ResourceManager.GetString("PersonalInformationICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PERSONAL INFORMATION.
        /// </summary>
        public static string PersonalInformationRepresentative {
            get {
                return ResourceManager.GetString("PersonalInformationRepresentative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PFX.
        /// </summary>
        public static string PFXScreening {
            get {
                return ResourceManager.GetString("PFXScreening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHONE.
        /// </summary>
        public static string PhoneICE {
            get {
                return ResourceManager.GetString("PhoneICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHONE.
        /// </summary>
        public static string PhoneMBRProvider {
            get {
                return ResourceManager.GetString("PhoneMBRProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHONE.
        /// </summary>
        public static string PhoneMemberAddress {
            get {
                return ResourceManager.GetString("PhoneMemberAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHONE.
        /// </summary>
        public static string PhoneRepresentative {
            get {
                return ResourceManager.GetString("PhoneRepresentative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHYSICIAN FIRST NAME.
        /// </summary>
        public static string PhysicianFirstNameMBRProvider {
            get {
                return ResourceManager.GetString("PhysicianFirstNameMBRProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHYSICIAN LAST NAME.
        /// </summary>
        public static string PhysicianLastNameMBRProvider {
            get {
                return ResourceManager.GetString("PhysicianLastNameMBRProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHYSICIAN MIDDLE NAME.
        /// </summary>
        public static string PhysicianMiddleNameMBRProvider {
            get {
                return ResourceManager.GetString("PhysicianMiddleNameMBRProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHYSICIAN NAME.
        /// </summary>
        public static string PhysicianNameMBRProvider {
            get {
                return ResourceManager.GetString("PhysicianNameMBRProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLAN ID.
        /// </summary>
        public static string PlanIDEligibility {
            get {
                return ResourceManager.GetString("PlanIDEligibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLAN ID.
        /// </summary>
        public static string PlanIDOveride {
            get {
                return ResourceManager.GetString("PlanIDOveride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GRP/PLAN.
        /// </summary>
        public static string PlanName {
            get {
                return ResourceManager.GetString("PlanName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLAN NAME.
        /// </summary>
        public static string PlanNameEligibility {
            get {
                return ResourceManager.GetString("PlanNameEligibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLAN-SUBGROUP.
        /// </summary>
        public static string PlanSubGroupHeader {
            get {
                return ResourceManager.GetString("PlanSubGroupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRE-EX CREDIT DAYS.
        /// </summary>
        public static string PreExCreditDaysEnrollment {
            get {
                return ResourceManager.GetString("PreExCreditDaysEnrollment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRE-EX END DATE.
        /// </summary>
        public static string PreExEndDateEnrollment {
            get {
                return ResourceManager.GetString("PreExEndDateEnrollment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRE-EX START DATE.
        /// </summary>
        public static string PreExStartDateEnrollment {
            get {
                return ResourceManager.GetString("PreExStartDateEnrollment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRE-EX.
        /// </summary>
        public static string PreExTitleEnrollment {
            get {
                return ResourceManager.GetString("PreExTitleEnrollment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PREF CALL TIME FROM.
        /// </summary>
        public static string PrefCallTimeFromPhoneDemoGraphics {
            get {
                return ResourceManager.GetString("PrefCallTimeFromPhoneDemoGraphics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PREF CALL TIME THRU.
        /// </summary>
        public static string PrefCallTimeThruPhoneDemoGraphics {
            get {
                return ResourceManager.GetString("PrefCallTimeThruPhoneDemoGraphics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PREF CALL DAYS.
        /// </summary>
        public static string PreferableCallDaysPhoneDemoGraphics {
            get {
                return ResourceManager.GetString("PreferableCallDaysPhoneDemoGraphics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHONE.
        /// </summary>
        public static string PrimaryContact {
            get {
                return ResourceManager.GetString("PrimaryContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRIOR BILLING EFF DATE.
        /// </summary>
        public static string PrioBillingEffDatedEnrollment {
            get {
                return ResourceManager.GetString("PrioBillingEffDatedEnrollment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRIOR BILLING INDICATOR.
        /// </summary>
        public static string PriorBillingIndicatorEnrollment {
            get {
                return ResourceManager.GetString("PriorBillingIndicatorEnrollment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QUALIFYING EVENT DATE.
        /// </summary>
        public static string QualifyingEventDateEnrollment {
            get {
                return ResourceManager.GetString("QualifyingEventDateEnrollment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RACE.
        /// </summary>
        public static string RaceDemoGraphics {
            get {
                return ResourceManager.GetString("RaceDemoGraphics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REASON.
        /// </summary>
        public static string ReasonEligibility {
            get {
                return ResourceManager.GetString("ReasonEligibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RECORD NO.
        /// </summary>
        public static string RecordNumberEnrollment {
            get {
                return ResourceManager.GetString("RecordNumberEnrollment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference ID.
        /// </summary>
        public static string ReferenceID {
            get {
                return ResourceManager.GetString("ReferenceID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REF#.
        /// </summary>
        public static string REFHEader {
            get {
                return ResourceManager.GetString("REFHEader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RELATIONSHIP.
        /// </summary>
        public static string RelationshipEnrollment {
            get {
                return ResourceManager.GetString("RelationshipEnrollment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RELATIONSHIP.
        /// </summary>
        public static string RelationshipICE {
            get {
                return ResourceManager.GetString("RelationshipICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RELIGION.
        /// </summary>
        public static string ReligionDemoGraphics {
            get {
                return ResourceManager.GetString("ReligionDemoGraphics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESIDENTIAL STATUS.
        /// </summary>
        public static string ResidentialStatusPhoneDemoGraphics {
            get {
                return ResourceManager.GetString("ResidentialStatusPhoneDemoGraphics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESULT.
        /// </summary>
        public static string ResultMedicare {
            get {
                return ResourceManager.GetString("ResultMedicare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEGMENT ID.
        /// </summary>
        public static string SegmentIDMedicare {
            get {
                return ResourceManager.GetString("SegmentIDMedicare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SFX.
        /// </summary>
        public static string SFXScreening {
            get {
                return ResourceManager.GetString("SFXScreening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPOKEN 1.
        /// </summary>
        public static string Spoken1PhoneDemoGraphics {
            get {
                return ResourceManager.GetString("Spoken1PhoneDemoGraphics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPOKEN 2.
        /// </summary>
        public static string Spoken2PhoneDemoGraphics {
            get {
                return ResourceManager.GetString("Spoken2PhoneDemoGraphics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSN.
        /// </summary>
        public static string SSNEnrollment {
            get {
                return ResourceManager.GetString("SSNEnrollment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STANDARD UNIQUE HEALTH ID.
        /// </summary>
        public static string StandardUniqueHealthIDEnrollment {
            get {
                return ResourceManager.GetString("StandardUniqueHealthIDEnrollment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STATE.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STATE.
        /// </summary>
        public static string StateICE {
            get {
                return ResourceManager.GetString("StateICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STATE.
        /// </summary>
        public static string StateMedicare {
            get {
                return ResourceManager.GetString("StateMedicare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STATE.
        /// </summary>
        public static string StateMemberAddress {
            get {
                return ResourceManager.GetString("StateMemberAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STATE.
        /// </summary>
        public static string StateRepresentative {
            get {
                return ResourceManager.GetString("StateRepresentative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STATUS.
        /// </summary>
        public static string StatusEnrollment {
            get {
                return ResourceManager.GetString("StatusEnrollment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STATUS.
        /// </summary>
        public static string StatusMember {
            get {
                return ResourceManager.GetString("StatusMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUB-GRP.
        /// </summary>
        public static string SubGroup {
            get {
                return ResourceManager.GetString("SubGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MBR#.
        /// </summary>
        public static string SubscriberIDHeader {
            get {
                return ResourceManager.GetString("SubscriberIDHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUBSIDY.
        /// </summary>
        public static string SubsidyEligibility {
            get {
                return ResourceManager.GetString("SubsidyEligibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUPPLEMENTAL DRUG TYPE.
        /// </summary>
        public static string SupplementalDrugType {
            get {
                return ResourceManager.GetString("SupplementalDrugType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TERM DATE.
        /// </summary>
        public static string TermDateEligibility {
            get {
                return ResourceManager.GetString("TermDateEligibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TYPE.
        /// </summary>
        public static string TypeMemberAddress {
            get {
                return ResourceManager.GetString("TypeMemberAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNITS.
        /// </summary>
        public static string UnitsOveride {
            get {
                return ResourceManager.GetString("UnitsOveride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VERIFIED DATE.
        /// </summary>
        public static string VerifiedDateMedicare {
            get {
                return ResourceManager.GetString("VerifiedDateMedicare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VOID EVENT.
        /// </summary>
        public static string VoidEventEligibility {
            get {
                return ResourceManager.GetString("VoidEventEligibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WORK.
        /// </summary>
        public static string WorkAddressEnrollment {
            get {
                return ResourceManager.GetString("WorkAddressEnrollment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WRITTEN 1.
        /// </summary>
        public static string Written1PhoneDemoGraphics {
            get {
                return ResourceManager.GetString("Written1PhoneDemoGraphics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WRITTEN 2.
        /// </summary>
        public static string Written2PhoneDemoGraphics {
            get {
                return ResourceManager.GetString("Written2PhoneDemoGraphics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZIP.
        /// </summary>
        public static string ZipCode {
            get {
                return ResourceManager.GetString("ZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZIP.
        /// </summary>
        public static string ZipICE {
            get {
                return ResourceManager.GetString("ZipICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZIP.
        /// </summary>
        public static string ZipMemberAddress {
            get {
                return ResourceManager.GetString("ZipMemberAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZIP.
        /// </summary>
        public static string ZipRepresentative {
            get {
                return ResourceManager.GetString("ZipRepresentative", resourceCulture);
            }
        }
    }
}
