//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AHC.CD.Entities.DatabaseDesign
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEAScheduleInfo
    {
        public DEAScheduleInfo()
        {
            this.FederalDEAInfo = new HashSet<FederalDEAInfo>();
            this.DEAScheduleTypes = new HashSet<DEAScheduleType>();
        }
    
        public int Id { get; set; }
        public System.DateTime LastUpdatedOn { get; set; }
    
        public virtual ICollection<FederalDEAInfo> FederalDEAInfo { get; set; }
        public virtual ICollection<DEAScheduleType> DEAScheduleTypes { get; set; }
    }
}
