using PortalTemplate.Areas.Billing.Models.EOB_Report;
using PortalTemplate.Areas.Billing.Services.IServices;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PortalTemplate.Areas.Billing.Services
{
    public class EOBReportService : IEOBReportService
    {
        public List<Models.EOB_Report.EOBReportRenderingProviderByDateOfServiceViewModel> GetEobReportOfRenderingProviderByDos()
        {
            List<EOBReportRenderingProviderByDateOfServiceViewModel> EOBReportRenderingProviderByDOSList = new List<EOBReportRenderingProviderByDateOfServiceViewModel>();

            EOBReportRenderingProviderByDOSList.Add(new EOBReportRenderingProviderByDateOfServiceViewModel { ID = 1, CPT = "99214", PrimaryPayerName = "STATE OF FLORIDA MADICAID", SecondaryPayerName = "", Check = "0.00", PatientName = "SANTIAGO TORR HERIBERT", DOS = new DateTime(2014, 12, 06), Billed = "554.00", Allowed = "0.00", Adjusted = "0.01", Denied = "0.00", CoInsurence = "0.00", Amount = "0.00", Penalty = "0.00", Paid = "0.00", Reason = "CO-45" });
            EOBReportRenderingProviderByDOSList.Add(new EOBReportRenderingProviderByDateOfServiceViewModel { ID = 2, CPT = "G6453", PrimaryPayerName = "STATE OF FLORIDA MADICAID", SecondaryPayerName = "", Check = "0.00", PatientName = "SANTIAGO TORR HERIBERT", DOS = new DateTime(2014, 11, 13), Billed = "199.00", Allowed = "0.00", Adjusted = "199.00", Denied = "0.00", CoInsurence = "0.00", Amount = "0.00", Penalty = "0.00", Paid = "0.00", Reason = "CO-45" });
            EOBReportRenderingProviderByDOSList.Add(new EOBReportRenderingProviderByDateOfServiceViewModel { ID = 3, CPT = "G2342", PrimaryPayerName = "STATE OF FLORIDA MADICAID", SecondaryPayerName = "", Check = "0.00", PatientName = "SANTIAGO TORR HERIBERT", DOS = new DateTime(2014, 12, 31), Billed = "324.00", Allowed = "0.00", Adjusted = "0.01", Denied = "0.00", CoInsurence = "0.00", Amount = "0.00", Penalty = "0.00", Paid = "0.00", Reason = "CO-16" });
            EOBReportRenderingProviderByDOSList.Add(new EOBReportRenderingProviderByDateOfServiceViewModel { ID = 4, CPT = "G5437", PrimaryPayerName = "STATE OF FLORIDA MADICAID", SecondaryPayerName = "", Check = "0.00", PatientName = "SANTIAGO TORR HERIBERT", DOS = new DateTime(2014, 10, 22), Billed = "124.00", Allowed = "0.00", Adjusted = "0.01", Denied = "0.00", CoInsurence = "0.00", Amount = "0.00", Penalty = "0.00", Paid = "0.00", Reason = "CO-45" });
            EOBReportRenderingProviderByDOSList.Add(new EOBReportRenderingProviderByDateOfServiceViewModel { ID = 5, CPT = "G7555", PrimaryPayerName = "STATE OF FLORIDA MADICAID", SecondaryPayerName = "", Check = "0.00", PatientName = "SANTIAGO TORR HERIBERT", DOS = new DateTime(2014, 12, 12), Billed = "104.00", Allowed = "0.00", Adjusted = "0.01", Denied = "0.00", CoInsurence = "0.00", Amount = "0.00", Penalty = "0.00", Paid = "0.00", Reason = "CO-16" });
            EOBReportRenderingProviderByDOSList.Add(new EOBReportRenderingProviderByDateOfServiceViewModel { ID = 6, CPT = "1232F", PrimaryPayerName = "STATE OF FLORIDA MADICAID", SecondaryPayerName = "", Check = "0.00", PatientName = "SANTIAGO TORR HERIBERT", DOS = new DateTime(2014, 11, 30), Billed = "542.00", Allowed = "0.00", Adjusted = "0.01", Denied = "0.00", CoInsurence = "0.00", Amount = "0.00", Penalty = "0.00", Paid = "0.00", Reason = "CO-54" });
            EOBReportRenderingProviderByDOSList.Add(new EOBReportRenderingProviderByDateOfServiceViewModel { ID = 7, CPT = "G6710", PrimaryPayerName = "STATE OF FLORIDA MADICAID", SecondaryPayerName = "", Check = "0.00", PatientName = "SANTIAGO TORR HERIBERT", DOS = new DateTime(2014, 12, 29), Billed = "244.00", Allowed = "0.00", Adjusted = "0.01", Denied = "0.00", CoInsurence = "0.00", Amount = "0.00", Penalty = "0.00", Paid = "0.00", Reason = "CO-256" });
            EOBReportRenderingProviderByDOSList.Add(new EOBReportRenderingProviderByDateOfServiceViewModel { ID = 8, CPT = "6543G", PrimaryPayerName = "STATE OF FLORIDA MADICAID", SecondaryPayerName = "", Check = "0.00", PatientName = "SIMPSON ALEX B", DOS = new DateTime(2014, 11, 16), Billed = "140.00", Allowed = "0.00", Adjusted = "140.00", Denied = "0.00", CoInsurence = "0.00", Amount = "0.00", Penalty = "0.00", Paid = "0.00", Reason = "CO-32" });
            EOBReportRenderingProviderByDOSList.Add(new EOBReportRenderingProviderByDateOfServiceViewModel { ID = 9, CPT = "H6754", PrimaryPayerName = "STATE OF FLORIDA MADICAID", SecondaryPayerName = "", Check = "0.00", PatientName = "SIMPSON ALEX B", DOS = new DateTime(2014, 09, 26), Billed = "223.00", Allowed = "0.00", Adjusted = "0.01", Denied = "0.00", CoInsurence = "0.00", Amount = "0.00", Penalty = "0.00", Paid = "0.00", Reason = "CO-16" });
            EOBReportRenderingProviderByDOSList.Add(new EOBReportRenderingProviderByDateOfServiceViewModel { ID = 10, CPT = "J6533", PrimaryPayerName = "STATE OF FLORIDA MADICAID", SecondaryPayerName = "", Check = "0.00", PatientName = "SIMPSON ALEX B", DOS = new DateTime(2014, 09, 23), Billed = "130.00", Allowed = "0.00", Adjusted = "0.01", Denied = "0.00", CoInsurence = "0.00", Amount = "0.00", Penalty = "0.00", Paid = "0.00", Reason = "CO-16" });
            return EOBReportRenderingProviderByDOSList;
        }

        public List<Models.EOB_Report.EOBReportRenderingProviderByPaymentDateViewModel> GetEobReportOfRenderingProviderByPaymentDate()
        {

            List<EOBReportRenderingProviderByPaymentDateViewModel> EOBReportRenderingProviderByPaymentDateList = new List<EOBReportRenderingProviderByPaymentDateViewModel>();

            EOBReportRenderingProviderByPaymentDateList.Add(new EOBReportRenderingProviderByPaymentDateViewModel { ID = 1, CPT = "99214", PrimaryPayerName = "STATE OF FLORIDA MADICAID", SecondaryPayerName = "", PaymentDate = new DateTime(2014, 11, 16), Check = "0.00", PatientName = "SANTIAGO TORR HERIBERT", DOS = new DateTime(2014, 12, 06), Billed = "554.00", Allowed = "0.00", Adjusted = "0.01", Denied = "0.00", CoInsurence = "0.00", Amount = "0.00", Penalty = "0.00", Paid = "0.00", Reason = "CO-45" });
            EOBReportRenderingProviderByPaymentDateList.Add(new EOBReportRenderingProviderByPaymentDateViewModel { ID = 2, CPT = "G6453", PrimaryPayerName = "STATE OF FLORIDA MADICAID", SecondaryPayerName = "", PaymentDate = new DateTime(2014, 09, 26), Check = "0.00", PatientName = "SANTIAGO TORR HERIBERT", DOS = new DateTime(2014, 11, 13), Billed = "199.00", Allowed = "0.00", Adjusted = "199.00", Denied = "0.00", CoInsurence = "0.00", Amount = "0.00", Penalty = "0.00", Paid = "0.00", Reason = "CO-45" });
            EOBReportRenderingProviderByPaymentDateList.Add(new EOBReportRenderingProviderByPaymentDateViewModel { ID = 3, CPT = "G2342", PrimaryPayerName = "STATE OF FLORIDA MADICAID", SecondaryPayerName = "", PaymentDate = new DateTime(2014, 09, 23), Check = "0.00", PatientName = "SANTIAGO TORR HERIBERT", DOS = new DateTime(2014, 12, 31), Billed = "324.00", Allowed = "0.00", Adjusted = "0.01", Denied = "0.00", CoInsurence = "0.00", Amount = "0.00", Penalty = "0.00", Paid = "0.00", Reason = "CO-16" });
            EOBReportRenderingProviderByPaymentDateList.Add(new EOBReportRenderingProviderByPaymentDateViewModel { ID = 4, CPT = "G5437", PrimaryPayerName = "STATE OF FLORIDA MADICAID", SecondaryPayerName = "", PaymentDate = new DateTime(2014, 12, 06), Check = "0.00", PatientName = "SANTIAGO TORR HERIBERT", DOS = new DateTime(2014, 10, 22), Billed = "124.00", Allowed = "0.00", Adjusted = "0.01", Denied = "0.00", CoInsurence = "0.00", Amount = "0.00", Penalty = "0.00", Paid = "0.00", Reason = "CO-45" });
            EOBReportRenderingProviderByPaymentDateList.Add(new EOBReportRenderingProviderByPaymentDateViewModel { ID = 5, CPT = "G7555", PrimaryPayerName = "STATE OF FLORIDA MADICAID", SecondaryPayerName = "", PaymentDate = new DateTime(2014, 11, 13), Check = "0.00", PatientName = "SANTIAGO TORR HERIBERT", DOS = new DateTime(2014, 12, 12), Billed = "104.00", Allowed = "0.00", Adjusted = "0.01", Denied = "0.00", CoInsurence = "0.00", Amount = "0.00", Penalty = "0.00", Paid = "0.00", Reason = "CO-16" });
            EOBReportRenderingProviderByPaymentDateList.Add(new EOBReportRenderingProviderByPaymentDateViewModel { ID = 6, CPT = "1232F", PrimaryPayerName = "STATE OF FLORIDA MADICAID", SecondaryPayerName = "", PaymentDate = new DateTime(2014, 12, 31), Check = "0.00", PatientName = "SANTIAGO TORR HERIBERT", DOS = new DateTime(2014, 11, 30), Billed = "542.00", Allowed = "0.00", Adjusted = "0.01", Denied = "0.00", CoInsurence = "0.00", Amount = "0.00", Penalty = "0.00", Paid = "0.00", Reason = "CO-54" });
            EOBReportRenderingProviderByPaymentDateList.Add(new EOBReportRenderingProviderByPaymentDateViewModel { ID = 7, CPT = "G6710", PrimaryPayerName = "STATE OF FLORIDA MADICAID", SecondaryPayerName = "", PaymentDate = new DateTime(2014, 10, 22), Check = "0.00", PatientName = "SANTIAGO TORR HERIBERT", DOS = new DateTime(2014, 12, 29), Billed = "244.00", Allowed = "0.00", Adjusted = "0.01", Denied = "0.00", CoInsurence = "0.00", Amount = "0.00", Penalty = "0.00", Paid = "0.00", Reason = "CO-256" });
            EOBReportRenderingProviderByPaymentDateList.Add(new EOBReportRenderingProviderByPaymentDateViewModel { ID = 8, CPT = "6543G", PrimaryPayerName = "STATE OF FLORIDA MADICAID", SecondaryPayerName = "", PaymentDate = new DateTime(2014, 12, 12), Check = "0.00", PatientName = "SIMPSON ALEX B", DOS = new DateTime(2014, 11, 16), Billed = "140.00", Allowed = "0.00", Adjusted = "140.00", Denied = "0.00", CoInsurence = "0.00", Amount = "0.00", Penalty = "0.00", Paid = "0.00", Reason = "CO-32" });
            EOBReportRenderingProviderByPaymentDateList.Add(new EOBReportRenderingProviderByPaymentDateViewModel { ID = 9, CPT = "H6754", PrimaryPayerName = "STATE OF FLORIDA MADICAID", SecondaryPayerName = "", PaymentDate = new DateTime(2014, 11, 30), Check = "0.00", PatientName = "SIMPSON ALEX B", DOS = new DateTime(2014, 09, 26), Billed = "223.00", Allowed = "0.00", Adjusted = "0.01", Denied = "0.00", CoInsurence = "0.00", Amount = "0.00", Penalty = "0.00", Paid = "0.00", Reason = "CO-16" });
            EOBReportRenderingProviderByPaymentDateList.Add(new EOBReportRenderingProviderByPaymentDateViewModel { ID = 10, CPT = "J6533", PrimaryPayerName = "STATE OF FLORIDA MADICAID", SecondaryPayerName = "", PaymentDate = new DateTime(2014, 12, 29), Check = "0.00", PatientName = "SIMPSON ALEX B", DOS = new DateTime(2014, 09, 23), Billed = "130.00", Allowed = "0.00", Adjusted = "0.01", Denied = "0.00", CoInsurence = "0.00", Amount = "0.00", Penalty = "0.00", Paid = "0.00", Reason = "CO-16" });
            return EOBReportRenderingProviderByPaymentDateList;
        }

        public List<Models.EOB_Report.EOBReportServiceLocationByDateOfServiceViewModel> GetEobReportOfServiceLocationByDos()
        {
            List<EOBReportServiceLocationByDateOfServiceViewModel> EOBReportServiceLocationByDOSList = new List<EOBReportServiceLocationByDateOfServiceViewModel>();

            EOBReportServiceLocationByDOSList.Add(new EOBReportServiceLocationByDateOfServiceViewModel { ID = 1, CPT = "99214", PrimaryPayerName = "STATE OF FLORIDA MADICAID", SecondaryPayerName = "", Check = "0.00", RenderingProviderName = "IVAN A RAMOS", DOS = new DateTime(2014, 12, 06), Billed = "554.00", Allowed = "0.00", Adjusted = "0.01", Denied = "0.00", CoInsurence = "0.00", Amount = "0.00", Penalty = "0.00", Paid = "0.00", Reason = "CO-45" });
            EOBReportServiceLocationByDOSList.Add(new EOBReportServiceLocationByDateOfServiceViewModel { ID = 2, CPT = "G6453", PrimaryPayerName = "STATE OF FLORIDA MADICAID", SecondaryPayerName = "", Check = "0.00", RenderingProviderName = "IVAN A RAMOS", DOS = new DateTime(2014, 11, 13), Billed = "199.00", Allowed = "0.00", Adjusted = "199.00", Denied = "0.00", CoInsurence = "0.00", Amount = "0.00", Penalty = "0.00", Paid = "0.00", Reason = "CO-45" });
            EOBReportServiceLocationByDOSList.Add(new EOBReportServiceLocationByDateOfServiceViewModel { ID = 3, CPT = "G2342", PrimaryPayerName = "STATE OF FLORIDA MADICAID", SecondaryPayerName = "", Check = "0.00", RenderingProviderName = "IVAN A RAMOS", DOS = new DateTime(2014, 12, 31), Billed = "324.00", Allowed = "0.00", Adjusted = "0.01", Denied = "0.00", CoInsurence = "0.00", Amount = "0.00", Penalty = "0.00", Paid = "0.00", Reason = "CO-16" });
            EOBReportServiceLocationByDOSList.Add(new EOBReportServiceLocationByDateOfServiceViewModel { ID = 4, CPT = "G5437", PrimaryPayerName = "STATE OF FLORIDA MADICAID", SecondaryPayerName = "", Check = "0.00", RenderingProviderName = "IVAN A RAMOS", DOS = new DateTime(2014, 10, 22), Billed = "124.00", Allowed = "0.00", Adjusted = "0.01", Denied = "0.00", CoInsurence = "0.00", Amount = "0.00", Penalty = "0.00", Paid = "0.00", Reason = "CO-45" });
            EOBReportServiceLocationByDOSList.Add(new EOBReportServiceLocationByDateOfServiceViewModel { ID = 5, CPT = "G7555", PrimaryPayerName = "STATE OF FLORIDA MADICAID", SecondaryPayerName = "", Check = "0.00", RenderingProviderName = "IVAN A RAMOS", DOS = new DateTime(2014, 12, 12), Billed = "104.00", Allowed = "0.00", Adjusted = "0.01", Denied = "0.00", CoInsurence = "0.00", Amount = "0.00", Penalty = "0.00", Paid = "0.00", Reason = "CO-16" });
            EOBReportServiceLocationByDOSList.Add(new EOBReportServiceLocationByDateOfServiceViewModel { ID = 6, CPT = "1232F", PrimaryPayerName = "STATE OF FLORIDA MADICAID", SecondaryPayerName = "", Check = "0.00", RenderingProviderName = "IVAN A RAMOS", DOS = new DateTime(2014, 11, 30), Billed = "542.00", Allowed = "0.00", Adjusted = "0.01", Denied = "0.00", CoInsurence = "0.00", Amount = "0.00", Penalty = "0.00", Paid = "0.00", Reason = "CO-54" });
            EOBReportServiceLocationByDOSList.Add(new EOBReportServiceLocationByDateOfServiceViewModel { ID = 7, CPT = "G6710", PrimaryPayerName = "STATE OF FLORIDA MADICAID", SecondaryPayerName = "", Check = "0.00", RenderingProviderName = "IVAN A RAMOS", DOS = new DateTime(2014, 12, 29), Billed = "244.00", Allowed = "0.00", Adjusted = "0.01", Denied = "0.00", CoInsurence = "0.00", Amount = "0.00", Penalty = "0.00", Paid = "0.00", Reason = "CO-256" });
            EOBReportServiceLocationByDOSList.Add(new EOBReportServiceLocationByDateOfServiceViewModel { ID = 8, CPT = "6543G", PrimaryPayerName = "STATE OF FLORIDA MADICAID", SecondaryPayerName = "", Check = "0.00", RenderingProviderName = "IVAN A RAMOS", DOS = new DateTime(2014, 11, 16), Billed = "140.00", Allowed = "0.00", Adjusted = "140.00", Denied = "0.00", CoInsurence = "0.00", Amount = "0.00", Penalty = "0.00", Paid = "0.00", Reason = "CO-32" });
            EOBReportServiceLocationByDOSList.Add(new EOBReportServiceLocationByDateOfServiceViewModel { ID = 9, CPT = "H6754", PrimaryPayerName = "STATE OF FLORIDA MADICAID", SecondaryPayerName = "", Check = "0.00", RenderingProviderName = "IVAN A RAMOS", DOS = new DateTime(2014, 09, 26), Billed = "223.00", Allowed = "0.00", Adjusted = "0.01", Denied = "0.00", CoInsurence = "0.00", Amount = "0.00", Penalty = "0.00", Paid = "0.00", Reason = "CO-16" });
            EOBReportServiceLocationByDOSList.Add(new EOBReportServiceLocationByDateOfServiceViewModel { ID = 10, CPT = "J6533", PrimaryPayerName = "STATE OF FLORIDA MADICAID", SecondaryPayerName = "", Check = "0.00", RenderingProviderName = "IVAN A RAMOS", DOS = new DateTime(2014, 09, 23), Billed = "130.00", Allowed = "0.00", Adjusted = "0.01", Denied = "0.00", CoInsurence = "0.00", Amount = "0.00", Penalty = "0.00", Paid = "0.00", Reason = "CO-16" });
            return EOBReportServiceLocationByDOSList;
        }

        public List<Models.EOB_Report.EOBReportServiceLocationByPaymentDateViewModel> GetEobReportOfServiceLocationByPaymentDate()
        {
            List<EOBReportServiceLocationByPaymentDateViewModel> EOBReportServiceLocationByPaymentDateList = new List<EOBReportServiceLocationByPaymentDateViewModel>();

            EOBReportServiceLocationByPaymentDateList.Add(new EOBReportServiceLocationByPaymentDateViewModel { ID = 1, CPT = "99214", PrimaryPayerName = "STATE OF FLORIDA MADICAID", SecondaryPayerName = "", PaymentDate = new DateTime(2014, 11, 16), Check = "0.00", RenderingProviderName = "IVAN A RAMOS", DOS = new DateTime(2014, 12, 06), Billed = "554.00", Allowed = "0.00", Adjusted = "0.01", Denied = "0.00", CoInsurence = "0.00", Amount = "0.00", Penalty = "0.00", Paid = "0.00", Reason = "CO-45" });
            EOBReportServiceLocationByPaymentDateList.Add(new EOBReportServiceLocationByPaymentDateViewModel { ID = 2, CPT = "G6453", PrimaryPayerName = "STATE OF FLORIDA MADICAID", SecondaryPayerName = "", PaymentDate = new DateTime(2014, 09, 26), Check = "0.00", RenderingProviderName = "IVAN A RAMOS", DOS = new DateTime(2014, 11, 13), Billed = "199.00", Allowed = "0.00", Adjusted = "199.00", Denied = "0.00", CoInsurence = "0.00", Amount = "0.00", Penalty = "0.00", Paid = "0.00", Reason = "CO-45" });
            EOBReportServiceLocationByPaymentDateList.Add(new EOBReportServiceLocationByPaymentDateViewModel { ID = 3, CPT = "G2342", PrimaryPayerName = "STATE OF FLORIDA MADICAID", SecondaryPayerName = "", PaymentDate = new DateTime(2014, 09, 23), Check = "0.00", RenderingProviderName = "IVAN A RAMOS", DOS = new DateTime(2014, 12, 31), Billed = "324.00", Allowed = "0.00", Adjusted = "0.01", Denied = "0.00", CoInsurence = "0.00", Amount = "0.00", Penalty = "0.00", Paid = "0.00", Reason = "CO-16" });
            EOBReportServiceLocationByPaymentDateList.Add(new EOBReportServiceLocationByPaymentDateViewModel { ID = 4, CPT = "G5437", PrimaryPayerName = "STATE OF FLORIDA MADICAID", SecondaryPayerName = "", PaymentDate = new DateTime(2014, 12, 06), Check = "0.00", RenderingProviderName = "IVAN A RAMOS", DOS = new DateTime(2014, 10, 22), Billed = "124.00", Allowed = "0.00", Adjusted = "0.01", Denied = "0.00", CoInsurence = "0.00", Amount = "0.00", Penalty = "0.00", Paid = "0.00", Reason = "CO-45" });
            EOBReportServiceLocationByPaymentDateList.Add(new EOBReportServiceLocationByPaymentDateViewModel { ID = 5, CPT = "G7555", PrimaryPayerName = "STATE OF FLORIDA MADICAID", SecondaryPayerName = "", PaymentDate = new DateTime(2014, 11, 13), Check = "0.00", RenderingProviderName = "IVAN A RAMOS", DOS = new DateTime(2014, 12, 12), Billed = "104.00", Allowed = "0.00", Adjusted = "0.01", Denied = "0.00", CoInsurence = "0.00", Amount = "0.00", Penalty = "0.00", Paid = "0.00", Reason = "CO-16" });
            EOBReportServiceLocationByPaymentDateList.Add(new EOBReportServiceLocationByPaymentDateViewModel { ID = 6, CPT = "1232F", PrimaryPayerName = "STATE OF FLORIDA MADICAID", SecondaryPayerName = "", PaymentDate = new DateTime(2014, 12, 31), Check = "0.00", RenderingProviderName = "IVAN A RAMOS", DOS = new DateTime(2014, 11, 30), Billed = "542.00", Allowed = "0.00", Adjusted = "0.01", Denied = "0.00", CoInsurence = "0.00", Amount = "0.00", Penalty = "0.00", Paid = "0.00", Reason = "CO-54" });
            EOBReportServiceLocationByPaymentDateList.Add(new EOBReportServiceLocationByPaymentDateViewModel { ID = 7, CPT = "G6710", PrimaryPayerName = "STATE OF FLORIDA MADICAID", SecondaryPayerName = "", PaymentDate = new DateTime(2014, 10, 22), Check = "0.00", RenderingProviderName = "IVAN A RAMOS", DOS = new DateTime(2014, 12, 29), Billed = "244.00", Allowed = "0.00", Adjusted = "0.01", Denied = "0.00", CoInsurence = "0.00", Amount = "0.00", Penalty = "0.00", Paid = "0.00", Reason = "CO-256" });
            EOBReportServiceLocationByPaymentDateList.Add(new EOBReportServiceLocationByPaymentDateViewModel { ID = 8, CPT = "6543G", PrimaryPayerName = "STATE OF FLORIDA MADICAID", SecondaryPayerName = "", PaymentDate = new DateTime(2014, 12, 12), Check = "0.00", RenderingProviderName = "IVAN A RAMOS", DOS = new DateTime(2014, 11, 16), Billed = "140.00", Allowed = "0.00", Adjusted = "140.00", Denied = "0.00", CoInsurence = "0.00", Amount = "0.00", Penalty = "0.00", Paid = "0.00", Reason = "CO-32" });
            EOBReportServiceLocationByPaymentDateList.Add(new EOBReportServiceLocationByPaymentDateViewModel { ID = 9, CPT = "H6754", PrimaryPayerName = "STATE OF FLORIDA MADICAID", SecondaryPayerName = "", PaymentDate = new DateTime(2014, 11, 30), Check = "0.00", RenderingProviderName = "IVAN A RAMOS", DOS = new DateTime(2014, 09, 26), Billed = "223.00", Allowed = "0.00", Adjusted = "0.01", Denied = "0.00", CoInsurence = "0.00", Amount = "0.00", Penalty = "0.00", Paid = "0.00", Reason = "CO-16" });
            EOBReportServiceLocationByPaymentDateList.Add(new EOBReportServiceLocationByPaymentDateViewModel { ID = 10, CPT = "J6533", PrimaryPayerName = "STATE OF FLORIDA MADICAID", SecondaryPayerName = "", PaymentDate = new DateTime(2014, 12, 29), Check = "0.00", RenderingProviderName = "IVAN A RAMOS", DOS = new DateTime(2014, 09, 23), Billed = "130.00", Allowed = "0.00", Adjusted = "0.01", Denied = "0.00", CoInsurence = "0.00", Amount = "0.00", Penalty = "0.00", Paid = "0.00", Reason = "CO-16" });
            return EOBReportServiceLocationByPaymentDateList;
        }
    }
}