//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AHC.CD.Entities.DatabaseDesign
{
    using System;
    using System.Collections.Generic;
    
    public partial class HomeAddress
    {
        public int Id { get; set; }
        public string Number { get; set; }
        public string ApartmentOrBuildingNumber { get; set; }
        public string Street { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public string County { get; set; }
        public string City { get; set; }
        public string ZipCode { get; set; }
        public bool IsPresentHomeAddress { get; set; }
        public System.DateTime LivingFrom { get; set; }
        public System.DateTime LivingTill { get; set; }
        public string AddressPreference { get; set; }
        public string Status { get; set; }
        public System.DateTime LastUpdatedOn { get; set; }
        public string PreferenceType { get; set; }
    }
}
