//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AHC.CD.Entities.DatabaseDesign
{
    using System;
    using System.Collections.Generic;
    
    public partial class HospitalContactPerson
    {
        public int Id { get; set; }
        public string ContactPersonName { get; set; }
        public string ContactPersonPhone { get; set; }
        public string ContactPersonFax { get; set; }
        public string Status { get; set; }
        public System.DateTime LastUpdatedOn { get; set; }
    
        public virtual HospitalPrivilege HospitalPrivilege { get; set; }
    }
}
