//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AHC.CD.Entities.DatabaseDesign
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhoneDetail
    {
        public int Id { get; set; }
        public string Number { get; set; }
        public string CountryCode { get; set; }
        public string Type { get; set; }
        public string Status { get; set; }
        public bool IsPrimary { get; set; }
        public System.DateTime LastUpdatedOn { get; set; }
    }
}
