//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AHC.CD.Entities.DatabaseDesign
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1Container : DbContext
    {
        public Model1Container()
            : base("name=Model1Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PersonalDetail> PersonalDetails { get; set; }
        public virtual DbSet<ProviderType> ProviderTypes { get; set; }
        public virtual DbSet<OtherLegalName> OtherLegalNames { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Profile> Profiles { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<HomeAddress> HomeAddresses { get; set; }
        public virtual DbSet<Hospital> Hospitals { get; set; }
        public virtual DbSet<HospitalContactInfo> HospitalContactInfoes { get; set; }
        public virtual DbSet<HospitalContactPerson> HospitalContactPersons { get; set; }
        public virtual DbSet<HospitalPrivilege> HospitalPrivileges { get; set; }
        public virtual DbSet<StaffCategory> StaffCategories { get; set; }
        public virtual DbSet<AdmittingPrivilege> AdmittingPrivileges { get; set; }
        public virtual DbSet<Specialty> Specialties { get; set; }
        public virtual DbSet<StateLicense> StateLicenses { get; set; }
        public virtual DbSet<StateLicenseType> StateLicenseTypes { get; set; }
        public virtual DbSet<StateLicenceStatus> StateLicenceStatus { get; set; }
        public virtual DbSet<FederalDEAInfo> FederalDEAInfoes { get; set; }
        public virtual DbSet<DEASchedule> DEASchedules { get; set; }
        public virtual DbSet<DEAScheduleType> DEAScheduleTypes { get; set; }
        public virtual DbSet<DEAScheduleInfo> DEAScheduleInfoes { get; set; }
        public virtual DbSet<MedicareMedicaidInfo> MedicareMedicaidInfoes { get; set; }
        public virtual DbSet<CDSCInfo> CDSCInfoes { get; set; }
        public virtual DbSet<OtherIdentification> OtherIdentifications { get; set; }
        public virtual DbSet<BirthInfo> BirthInfoes { get; set; }
        public virtual DbSet<PersonalIdentification> PersonalIdentifications { get; set; }
        public virtual DbSet<VisaDetail> VisaDetails { get; set; }
        public virtual DbSet<LanguageInfo> LanguageInfoes { get; set; }
        public virtual DbSet<ContactDetails> ContactDetails { get; set; }
        public virtual DbSet<PhoneDetail> PhoneDetails { get; set; }
        public virtual DbSet<EmailDetail> EmailDetails { get; set; }
        public virtual DbSet<Dcocuments> Dcocuments { get; set; }
        public virtual DbSet<StateLice> StateLice { get; set; }
        public virtual DbSet<Profile1> Profile1 { get; set; }
        public virtual DbSet<ProfessionalLiabilty> ProfessionalLiabilties { get; set; }
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<UserInfo> UserInfoes { get; set; }
        public virtual DbSet<SpouseName> SpouseNames { get; set; }
        public virtual DbSet<DocumentCategory> DocumentCategories { get; set; }
    }
}
