//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalTemplate.Areas.UM.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Content {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Content() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PortalTemplate.Areas.UM.App_LocalResources.Content", typeof(Content).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABV.
        /// </summary>
        public static string ABV {
            get {
                return ResourceManager.GetString("ABV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Member ID.
        /// </summary>
        public static string AccessMemberID {
            get {
                return ResourceManager.GetString("AccessMemberID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACT LOS.
        /// </summary>
        public static string ACTLOS {
            get {
                return ResourceManager.GetString("ACTLOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACTUAL LOS.
        /// </summary>
        public static string ACTUALLOS {
            get {
                return ResourceManager.GetString("ACTUALLOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTERNATE PLAN OF CARE.
        /// </summary>
        public static string AlternaltePlanOfCare {
            get {
                return ResourceManager.GetString("AlternaltePlanOfCare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APP DATE.
        /// </summary>
        public static string APPDATE {
            get {
                return ResourceManager.GetString("APPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APPROVED DAYS.
        /// </summary>
        public static string APPROVEDDAYS {
            get {
                return ResourceManager.GetString("APPROVEDDAYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APPROVED LOS.
        /// </summary>
        public static string APPROVEDLOS {
            get {
                return ResourceManager.GetString("APPROVEDLOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASSIGNED.
        /// </summary>
        public static string ASSIGNED {
            get {
                return ResourceManager.GetString("ASSIGNED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach Document.
        /// </summary>
        public static string AttachDocument {
            get {
                return ResourceManager.GetString("AttachDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUTH.
        /// </summary>
        public static string AUTH {
            get {
                return ResourceManager.GetString("AUTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUTH NO.
        /// </summary>
        public static string AUTHNO {
            get {
                return ResourceManager.GetString("AUTHNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUTH NOTE.
        /// </summary>
        public static string AUTHNOTE {
            get {
                return ResourceManager.GetString("AUTHNOTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BATCH NUMBER.
        /// </summary>
        public static string BATCHNUMBER {
            get {
                return ResourceManager.GetString("BATCHNUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Detail.
        /// </summary>
        public static string ContactDetail {
            get {
                return ResourceManager.GetString("ContactDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Name.
        /// </summary>
        public static string ContactName {
            get {
                return ResourceManager.GetString("ContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Type.
        /// </summary>
        public static string ContactType {
            get {
                return ResourceManager.GetString("ContactType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPT LIST.
        /// </summary>
        public static string CPTLIST {
            get {
                return ResourceManager.GetString("CPTLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        public static string CreatedBy {
            get {
                return ResourceManager.GetString("CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Date.
        /// </summary>
        public static string CreatedDate {
            get {
                return ResourceManager.GetString("CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRITERIA USED.
        /// </summary>
        public static string CriteriaUsed {
            get {
                return ResourceManager.GetString("CriteriaUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date and Time of Call.
        /// </summary>
        public static string DateandTimeofCall {
            get {
                return ResourceManager.GetString("DateandTimeofCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATE OF SVC.
        /// </summary>
        public static string DATEOFSVC {
            get {
                return ResourceManager.GetString("DATEOFSVC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DAYS REQ.
        /// </summary>
        public static string DAYSREQ {
            get {
                return ResourceManager.GetString("DAYSREQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECISION.
        /// </summary>
        public static string Decision {
            get {
                return ResourceManager.GetString("Decision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOC.
        /// </summary>
        public static string DOC {
            get {
                return ResourceManager.GetString("DOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Name.
        /// </summary>
        public static string DocumentName {
            get {
                return ResourceManager.GetString("DocumentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Type.
        /// </summary>
        public static string DocumentType {
            get {
                return ResourceManager.GetString("DocumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOS.
        /// </summary>
        public static string DOS {
            get {
                return ResourceManager.GetString("DOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DURATION.
        /// </summary>
        public static string DURATION {
            get {
                return ResourceManager.GetString("DURATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DX.
        /// </summary>
        public static string DX {
            get {
                return ResourceManager.GetString("DX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DX DESC.
        /// </summary>
        public static string DXDESC {
            get {
                return ResourceManager.GetString("DXDESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity.
        /// </summary>
        public static string Entity {
            get {
                return ResourceManager.GetString("Entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity Type.
        /// </summary>
        public static string EntityType {
            get {
                return ResourceManager.GetString("EntityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENTRY.
        /// </summary>
        public static string ENTRY {
            get {
                return ResourceManager.GetString("ENTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXP DOA.
        /// </summary>
        public static string EXPDOA {
            get {
                return ResourceManager.GetString("EXPDOA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXP DC.
        /// </summary>
        public static string EXPDOC {
            get {
                return ResourceManager.GetString("EXPDOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FACILITY.
        /// </summary>
        public static string FACILITY {
            get {
                return ResourceManager.GetString("FACILITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FROM.
        /// </summary>
        public static string FROMDATE {
            get {
                return ResourceManager.GetString("FROMDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GENERATED DATE.
        /// </summary>
        public static string GENERATEDDATE {
            get {
                return ResourceManager.GetString("GENERATEDDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HICN.
        /// </summary>
        public static string HICN {
            get {
                return ResourceManager.GetString("HICN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inc Fax.
        /// </summary>
        public static string IncFax {
            get {
                return ResourceManager.GetString("IncFax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Modified Date.
        /// </summary>
        public static string LastModifiedDate {
            get {
                return ResourceManager.GetString("LastModifiedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LETTER REASON.
        /// </summary>
        public static string LETTERREASON {
            get {
                return ResourceManager.GetString("LETTERREASON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LIST OF MEDICAL SERVICE.
        /// </summary>
        public static string ListOfMedicalService {
            get {
                return ResourceManager.GetString("ListOfMedicalService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MBR ID.
        /// </summary>
        public static string MBRID {
            get {
                return ResourceManager.GetString("MBRID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MBR NAME.
        /// </summary>
        public static string MBRNAME {
            get {
                return ResourceManager.GetString("MBRNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medicaid.
        /// </summary>
        public static string Medicaid {
            get {
                return ResourceManager.GetString("Medicaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member ID.
        /// </summary>
        public static string MemberID {
            get {
                return ResourceManager.GetString("MemberID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MODULE.
        /// </summary>
        public static string Module {
            get {
                return ResourceManager.GetString("Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Name.
        /// </summary>
        public static string ModuleName {
            get {
                return ResourceManager.GetString("ModuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outcome.
        /// </summary>
        public static string Outcome {
            get {
                return ResourceManager.GetString("Outcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outcome Type.
        /// </summary>
        public static string OutcomeType {
            get {
                return ResourceManager.GetString("OutcomeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUTPATIENT TYPE.
        /// </summary>
        public static string OUTPATIENTTYPE {
            get {
                return ResourceManager.GetString("OUTPATIENTTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POS.
        /// </summary>
        public static string POS {
            get {
                return ResourceManager.GetString("POS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRIMARY DX.
        /// </summary>
        public static string PRIMARYDX {
            get {
                return ResourceManager.GetString("PRIMARYDX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROVIDER.
        /// </summary>
        public static string PROVIDER {
            get {
                return ResourceManager.GetString("PROVIDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROVIDER ID.
        /// </summary>
        public static string PROVIDERID {
            get {
                return ResourceManager.GetString("PROVIDERID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RATIONALE.
        /// </summary>
        public static string Rationale {
            get {
                return ResourceManager.GetString("Rationale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REF#.
        /// </summary>
        public static string REF {
            get {
                return ResourceManager.GetString("REF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference ID.
        /// </summary>
        public static string ReferenceID {
            get {
                return ResourceManager.GetString("ReferenceID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REQ.
        /// </summary>
        public static string REQ {
            get {
                return ResourceManager.GetString("REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REQUEST.
        /// </summary>
        public static string REQUEST {
            get {
                return ResourceManager.GetString("REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REQ UNITS.
        /// </summary>
        public static string REQUNITS {
            get {
                return ResourceManager.GetString("REQUNITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REVIEW.
        /// </summary>
        public static string REVIEW {
            get {
                return ResourceManager.GetString("REVIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REVIEW DT.
        /// </summary>
        public static string REVIEWDT {
            get {
                return ResourceManager.GetString("REVIEWDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REVIEW TYPE.
        /// </summary>
        public static string ReviewType {
            get {
                return ResourceManager.GetString("ReviewType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SVC SUBJECT TO NOTICE.
        /// </summary>
        public static string ServiceSubjectToNotice {
            get {
                return ResourceManager.GetString("ServiceSubjectToNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STATUS.
        /// </summary>
        public static string STATUS {
            get {
                return ResourceManager.GetString("STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SVC PROVIDER.
        /// </summary>
        public static string SVCPROVIDER {
            get {
                return ResourceManager.GetString("SVCPROVIDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOC.
        /// </summary>
        public static string TOC {
            get {
                return ResourceManager.GetString("TOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TO.
        /// </summary>
        public static string TODATE {
            get {
                return ResourceManager.GetString("TODATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOS.
        /// </summary>
        public static string TOS {
            get {
                return ResourceManager.GetString("TOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTAL AUTHED.
        /// </summary>
        public static string TOTALAUTHED {
            get {
                return ResourceManager.GetString("TOTALAUTHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTAL DENIED.
        /// </summary>
        public static string TOTALDENIED {
            get {
                return ResourceManager.GetString("TOTALDENIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNITS.
        /// </summary>
        public static string UNITS {
            get {
                return ResourceManager.GetString("UNITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USERNAME.
        /// </summary>
        public static string USERNAME {
            get {
                return ResourceManager.GetString("USERNAME", resourceCulture);
            }
        }
    }
}
