//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AHC.CD.Entities.DatabaseDesign
{
    using System;
    using System.Collections.Generic;
    
    public partial class FederalDEAInfo
    {
        public FederalDEAInfo()
        {
            this.DEAScheduleInfoes = new HashSet<DEAScheduleInfo>();
        }
    
        public int Id { get; set; }
        public string Number { get; set; }
        public string RegistrationState { get; set; }
        public System.DateTime IssueDate { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public bool IsInGoodStanding { get; set; }
        public string LimitedOrRestricted { get; set; }
        public string RestrictionExplanation { get; set; }
        public bool HasSCRCertificate { get; set; }
        public string CertificatePath { get; set; }
        public string Status { get; set; }
        public System.DateTime LastUpdatedOn { get; set; }
    
        public virtual ICollection<DEAScheduleInfo> DEAScheduleInfoes { get; set; }
    }
}
