{
    "Languages" :[
      { "code": "ab", "name": "Abkhaz-аҧсуа" },
      { "code": "aa", "name": "Afar-Afaraf" },
      { "code": "af", "name": "Afrikaans-Afrikaans" },
      { "code": "ak", "name": "Akan-Akan" },
      { "code": "sq", "name": "Albanian-Shqip" },
      { "code": "am", "name": "Amharic-አማርኛ" },
      { "code": "ar", "name": "Arabic-العربية" },
      { "code": "an", "name": "Aragonese-Aragonés" },
      { "code": "hy", "name": "Armenian-Հայերեն" },
      { "code": "as", "name": "Assamese-অসমীয়া" },
      { "code": "av", "name": "Avaric-авар мацӀ, магӀарул мацӀ" },
      { "code": "ae", "name": "Avestan-avesta" },
      { "code": "ay", "name": "Aymara-aymar aru" },
      { "code": "az", "name": "Azerbaijani-azərbaycan dili" },
      { "code": "bm", "name": "Bambara-bamanankan" },
      { "code": "ba", "name": "Bashkir-башҡорт теле" },
      { "code": "eu", "name": "Basque-euskara, euskera" },
      { "code": "be", "name": "Belarusian-Беларуская" },
      { "code": "bn", "name": "Bengali-বাংলা" },
      { "code": "bh", "name": "Bihari-भोजपुरी" },
      { "code": "bi", "name": "Bislama-Bislama" },
      { "code": "bs", "name": "Bosnian-bosanski jezik" },
      { "code": "br", "name": "Breton-brezhoneg" },
      { "code": "bg", "name": "Bulgarian-български език" },
      { "code": "my", "name": "Burmese-ဗမာစာ" },
      { "code": "ca", "name": "Catalan; Valencian-Català" },
      { "code": "ch", "name": "Chamorro-Chamoru" },
      { "code": "ce", "name": "Chechen-нохчийн мотт" },
      { "code": "ny", "name": "Chichewa; Chewa; Nyanja-chiCheŵa, chinyanja" },
      { "code": "zh", "name": "Chinese-中文 (Zhōngwén), 汉语, 漢語" },
      { "code": "cv", "name": "Chuvash-чӑваш чӗлхи" },
      { "code": "kw", "name": "Cornish-Kernewek" },
      { "code": "co", "name": "Corsican-corsu, lingua corsa" },
      { "code": "cr", "name": "Cree-ᓀᐦᐃᔭᐍᐏᐣ" },
      { "code": "hr", "name": "Croatian-hrvatski" },
      { "code": "cs", "name": "Czech-česky, čeština" },
      { "code": "da", "name": "Danish-dansk" },
      { "code": "dv", "name": "Divehi; Dhivehi; Maldivian;-ދިވެހި" },
      { "code": "nl", "name": "Dutch-Nederlands, Vlaams" },
      { "code": "en", "name": "English-English" },
      { "code": "eo", "name": "Esperanto-Esperanto" },
      { "code": "et", "name": "Estonian-eesti, eesti keel" },
      { "code": "ee", "name": "Ewe-Eʋegbe" },
      { "code": "fo", "name": "Faroese-føroyskt" },
      { "code": "fj", "name": "Fijian-vosa Vakaviti" },
      { "code": "fi", "name": "Finnish-suomi, suomen kieli" },
      { "code": "fr", "name": "French-français, langue française" },
      { "code": "ff", "name": "Fula; Fulah; Pulaar; Pular-Fulfulde, Pulaar, Pular" },
      { "code": "gl", "name": "Galician-Galego" },
      { "code": "ka", "name": "Georgian-ქართული" },
      { "code": "de", "name": "German-Deutsch" },
      { "code": "el", "name": "Greek, Modern-Ελληνικά" },
      { "code": "gn", "name": "Guaraní-Avañeẽ" },
      { "code": "gu", "name": "Gujarati-ગુજરાતી" },
      { "code": "ht", "name": "Haitian; Haitian Creole-Kreyòl ayisyen" },
      { "code": "ha", "name": "Hausa-Hausa, هَوُسَ" },
      { "code": "he", "name": "Hebrew (modern)-עברית" },
      { "code": "hz", "name": "Herero-Otjiherero" },
      { "code": "hi", "name": "Hindi-हिन्दी, हिंदी" },
      { "code": "ho", "name": "Hiri Motu-Hiri Motu" },
      { "code": "hu", "name": "Hungarian-Magyar" },
      { "code": "ia", "name": "Interlingua-Interlingua" },
      { "code": "id", "name": "Indonesian-Bahasa Indonesia" },
      { "code": "ie", "name": "Interlingue-Originally called Occidental; then Interlingue after WWII" },
      { "code": "ga", "name": "Irish-Gaeilge" },
      { "code": "ig", "name": "Igbo-Asụsụ Igbo" },
      { "code": "ik", "name": "Inupiaq-Iñupiaq, Iñupiatun" },
      { "code": "io", "name": "Ido-Ido" },
      { "code": "is", "name": "Icelandic-Íslenska" },
      { "code": "it", "name": "Italian-Italiano" },
      { "code": "iu", "name": "Inuktitut-ᐃᓄᒃᑎᑐᑦ" },
      { "code": "ja", "name": "Japanese-日本語 (にほんご／にっぽんご)" },
      { "code": "jv", "name": "Javanese-basa Jawa" },
      { "code": "kl", "name": "Kalaallisut, Greenlandic-kalaallisut, kalaallit oqaasii" },
      { "code": "kn", "name": "Kannada-ಕನ್ನಡ" },
      { "code": "kr", "name": "Kanuri-Kanuri" },
      { "code": "ks", "name": "Kashmiri-कश्मीरी, كشميري‎" },
      { "code": "kk", "name": "Kazakh-Қазақ тілі" },
      { "code": "km", "name": "Khmer-ភាសាខ្មែរ" },
      { "code": "ki", "name": "Kikuyu, Gikuyu-Gĩkũyũ" },
      { "code": "rw", "name": "Kinyarwanda-Ikinyarwanda" },
      { "code": "ky", "name": "Kirghiz, Kyrgyz-кыргыз тили" },
      { "code": "kv", "name": "Komi-коми кыв" },
      { "code": "kg", "name": "Kongo-KiKongo" },
      { "code": "ko", "name": "Korean-한국어 (韓國語), 조선말 (朝鮮語)" },
      { "code": "ku", "name": "Kurdish-Kurdî, كوردی‎" },
      { "code": "kj", "name": "Kwanyama, Kuanyama-Kuanyama" },
      { "code": "la", "name": "Latin-latine, lingua latina" },
      { "code": "lb", "name": "Luxembourgish, Letzeburgesch-Lëtzebuergesch" },
      { "code": "lg", "name": "Luganda-Luganda" },
      { "code": "li", "name": "Limburgish, Limburgan, Limburger-Limburgs" },
      { "code": "ln", "name": "Lingala-Lingála" },
      { "code": "lo", "name": "Lao-ພາສາລາວ" },
      { "code": "lt", "name": "Lithuanian-lietuvių kalba" },
      { "code": "lu", "name": "Luba-Katanga-" },
      { "code": "lv", "name": "Latvian-latviešu valoda" },
      { "code": "gv", "name": "Manx-Gaelg, Gailck" },
      { "code": "mk", "name": "Macedonian-македонски јазик" },
      { "code": "mg", "name": "Malagasy-Malagasy fiteny" },
      { "code": "ms", "name": "Malay-bahasa Melayu, بهاس ملايو‎" },
      { "code": "ml", "name": "Malayalam-മലയാളം" },
      { "code": "mt", "name": "Maltese-Malti" },
      { "code": "mi", "name": "Māori-te reo Māori" },
      { "code": "mr", "name": "Marathi (Marāṭhī)-मराठी" },
      { "code": "mh", "name": "Marshallese-Kajin M̧ajeļ" },
      { "code": "mn", "name": "Mongolian-монгол" },
      { "code": "na", "name": "Nauru-Ekakairũ Naoero" },
      { "code": "nv", "name": "Navajo, Navaho-Diné bizaad, Dinékʼehǰí" },
      { "code": "nb", "name": "Norwegian Bokmål-Norsk bokmål" },
      { "code": "nd", "name": "North Ndebele-isiNdebele" },
      { "code": "ne", "name": "Nepali-नेपाली" },
      { "code": "ng", "name": "Ndonga-Owambo" },
      { "code": "nn", "name": "Norwegian Nynorsk-Norsk nynorsk" },
      { "code": "no", "name": "Norwegian-Norsk" },
      { "code": "ii", "name": "Nuosu-ꆈꌠ꒿ Nuosuhxop" },
      { "code": "nr", "name": "South Ndebele-isiNdebele" },
      { "code": "oc", "name": "Occitan-Occitan" },
      { "code": "oj", "name": "Ojibwe, Ojibwa-ᐊᓂᔑᓈᐯᒧᐎᓐ" },
      { "code": "cu", "name": "Old Church Slavonic, Church Slavic, Church Slavonic, Old Bulgarian, Old Slavonic-ѩзыкъ словѣньскъ" },
      { "code": "om", "name": "Oromo-Afaan Oromoo" },
      { "code": "or", "name": "Oriya-ଓଡ଼ିଆ" },
      { "code": "os", "name": "Ossetian, Ossetic-ирон æвзаг" },
      { "code": "pa", "name": "Panjabi, Punjabi-ਪੰਜਾਬੀ, پنجابی‎" },
      { "code": "pi", "name": "Pāli-पाऴि" },
      { "code": "fa", "name": "Persian-فارسی" },
      { "code": "pl", "name": "Polish-polski" },
      { "code": "ps", "name": "Pashto, Pushto-پښتو" },
      { "code": "pt", "name": "Portuguese-Português" },
      { "code": "qu", "name": "Quechua-Runa Simi, Kichwa" },
      { "code": "rm", "name": "Romansh-rumantsch grischun" },
      { "code": "rn", "name": "Kirundi-kiRundi" },
      { "code": "ro", "name": "Romanian, Moldavian, Moldovan-română" },
      { "code": "ru", "name": "Russian-русский язык" },
      { "code": "sa", "name": "Sanskrit (Saṁskṛta)-संस्कृतम्" },
      { "code": "sc", "name": "Sardinian-sardu" },
      { "code": "sd", "name": "Sindhi-सिन्धी, سنڌي، سندھی‎" },
      { "code": "se", "name": "Northern Sami-Davvisámegiella" },
      { "code": "sm", "name": "Samoan-gagana faa Samoa" },
      { "code": "sg", "name": "Sango-yângâ tî sängö" },
      { "code": "sr", "name": "Serbian-српски језик" },
      { "code": "gd", "name": "Scottish Gaelic; Gaelic-Gàidhlig" },
      { "code": "sn", "name": "Shona-chiShona" },
      { "code": "si", "name": "Sinhala, Sinhalese-සිංහල" },
      { "code": "sk", "name": "Slovak-slovenčina" },
      { "code": "sl", "name": "Slovene-slovenščina" },
      { "code": "so", "name": "Somali-Soomaaliga, af Soomaali" },
      { "code": "st", "name": "Southern Sotho-Sesotho" },
      { "code": "es", "name": "Spanish; Castilian-español, castellano" },
      { "code": "su", "name": "Sundanese-Basa Sunda" },
      { "code": "sw", "name": "Swahili-Kiswahili" },
      { "code": "ss", "name": "Swati-SiSwati" },
      { "code": "sv", "name": "Swedish-svenska" },
      { "code": "ta", "name": "Tamil-தமிழ்" },
      { "code": "te", "name": "Telugu-తెలుగు" },
      { "code": "tg", "name": "Tajik-тоҷикӣ, toğikī, تاجیکی‎" },
      { "code": "th", "name": "Thai-ไทย" },
      { "code": "ti", "name": "Tigrinya-ትግርኛ" },
      { "code": "bo", "name": "Tibetan Standard, Tibetan, Central-བོད་ཡིག" },
      { "code": "tk", "name": "Turkmen-Türkmen, Түркмен" },
      { "code": "tl", "name": "Tagalog-Wikang Tagalog, ᜏᜒᜃᜅ᜔ ᜆᜄᜎᜓᜄ᜔" },
      { "code": "tn", "name": "Tswana-Setswana" },
      { "code": "to", "name": "Tonga (Tonga Islands)-faka Tonga" },
      { "code": "tr", "name": "Turkish-Türkçe" },
      { "code": "ts", "name": "Tsonga-Xitsonga" },
      { "code": "tt", "name": "Tatar-татарча, tatarça, تاتارچا‎" },
      { "code": "tw", "name": "Twi-Twi" },
      { "code": "ty", "name": "Tahitian-Reo Tahiti" },
      { "code": "ug", "name": "Uighur, Uyghur-Uyƣurqə, ئۇيغۇرچە‎" },
      { "code": "uk", "name": "Ukrainian-українська" },
      { "code": "ur", "name": "Urdu-اردو" },
      { "code": "uz", "name": "Uzbek-zbek, Ўзбек, أۇزبېك‎" },
      { "code": "ve", "name": "Venda-Tshivenḓa" },
      { "code": "vi", "name": "Vietnamese-Tiếng Việt" },
      { "code": "vo", "name": "Volapük-Volapük" },
      { "code": "wa", "name": "Walloon-Walon" },
      { "code": "cy", "name": "Welsh-Cymraeg" },
      { "code": "wo", "name": "Wolof-Wollof" },
      { "code": "fy", "name": "Western Frisian-Frysk" },
      { "code": "xh", "name": "Xhosa-isiXhosa" },
      { "code": "yi", "name": "Yiddish-ייִדיש" },
      { "code": "yo", "name": "Yoruba-Yorùbá" },
      { "code": "za", "name": "Zhuang, Chuang-Saɯ cueŋƅ, Saw cuengh" }
    ]
}