{
    "addeditfields":[        
       " Name",
       "CODE", 
       "City Code",
       "Latitude",
        "Longitude",
        "County ",
        "State",
        "Country",
    ],
    "columns": [
        "Name",
        "Code",
        "City Code",
        "Latitude",
        "Longitude",
        "County ",
        "State",
        "Country",
        "Last Modified Date",
       
    ],
    "data": [
    [
      "Springfield",
      "SP001",
      "SP",
      "78",
      "45",
      "Missouri",
      "Kansas",
      "USA",
      "2011/04/25",
    ],
     [ 
      "Spring Hill",
      " SH0001",
      "SH",
      "28°28′44″N",
      "82°32′52″W",
      "Hernando",
      " Florida",
      "USA",
      "2011/04/25",
     ],
       [
      " New York",
      " NY0002",
      "NY",
      "40°42′46″N",
      "74°00′21″W",
      "New York (Manhattan)",
      " New York",
      "USA",
      "2011/04/25",
       ],
        [
      "San Francisco",
      " SF0003",
      "SF",
      "37°47′N ",
      "122°25′W",
      "San Jose–San Francisco–Oakland",
      " California  ",
      "USA",
      "2011/04/25",
        ],
    
    ]
}	