var scheduleEncounters =
    [
        {
            "ENCTRID": "116244951 ",
            "MBRID": "1607132022",
            "MBRLASTNAME": "Oliver",
            "MBRFIRSTNAME": "Kameisha",
            "NPI": "3282556434",
            "PRVDRLASTNAME": "Rubino",
            "PRVDRFIRSTNAME": "Ignazio",
            "FACILITY": "ALL SAINTS...",
            "DOS": "08/02/2016",
            "DOC": "08/10/2016",
            "CREATEDBY": "McCarthy",
            "ENCOUNTERTYPE": "HMO",
            "STATUS": "SCHEDULED",
            "ACTION": ""
        },
       {
           "ENCTRID": "116244952",
           "MBRID": "1607132022",
           "MBRLASTNAME": "Oliver",
           "MBRFIRSTNAME": "Kameisha",
           "NPI": "3282556434",
           "PRVDRLASTNAME": "Rubino",
           "PRVDRFIRSTNAME": "Ignazio",
           "FACILITY": "ALL SAINTS...",
           "DOS": "10/02/2016",
           "DOC": "08/10/2016",
           "CREATEDBY": "McCarthy",
           "ENCOUNTERTYPE": "MEDICARE",
           "STATUS": "RESCHEDULED",
           "ACTION": ""
       },
       {
           "ENCTRID": "116244953",
           "MBRID": "1607132022",
           "MBRLASTNAME": "Oliver",
           "MBRFIRSTNAME": "Kameisha",
           "NPI": "3282556434",
           "PRVDRLASTNAME": "Rubino",
           "PRVDRFIRSTNAME": "Ignazio",
           "FACILITY": "ALL SAINTS...",
           "DOS": "08/02/2016",
           "DOC": "08/10/2016",
           "CREATEDBY": "McCarthy",
           "ENCOUNTERTYPE": "HMO",
           "STATUS": "SCHEDULED",
           "ACTION": ""
       },
       {
           "ENCTRID": "116244954",
           "MBRID": "1607132022",
           "MBRLASTNAME": "Oliver",
           "MBRFIRSTNAME": "Kameisha",
           "NPI": "3282556434",
           "PRVDRLASTNAME": "Rubino",
           "PRVDRFIRSTNAME": "Ignazio",
           "FACILITY": "ALL SAINTS...",
           "DOS": "08/02/2016",
           "DOC": "08/10/2016",
           "CREATEDBY": "McCarthy",
           "ENCOUNTERTYPE": "MEDICARE",
           "STATUS": "SCHEDULED",
           "ACTION": ""
       },
       {
           "ENCTRID": "116244955",
           "MBRID": "1607132022",
           "MBRLASTNAME": "Oliver",
           "MBRFIRSTNAME": "Kameisha",
           "NPI": "3282556434",
           "PRVDRLASTNAME": "Rubino",
           "PRVDRFIRSTNAME": "Ignazio",
           "FACILITY": "ALL SAINTS...",
           "DOS": "10/02/2016",
           "DOC": "08/10/2016",
           "CREATEDBY": "McCarthy",
           "ENCOUNTERTYPE": "HMO",
           "STATUS": "RESCHEDULED",
           "ACTION": ""
       },
       {
           "ENCTRID": "116244956",
           "MBRID": "1607132022",
           "MBRLASTNAME": "Oliver",
           "MBRFIRSTNAME": "Kameisha",
           "NPI": "3282556434",
           "PRVDRLASTNAME": "Rubino",
           "PRVDRFIRSTNAME": "Ignazio",
           "FACILITY": "ALL SAINTS...",
           "DOS": "08/02/2016",
           "DOC": "08/10/2016",
           "CREATEDBY": "McCarthy",
           "ENCOUNTERTYPE": "MEDICARE",
           "STATUS": "SCHEDULED",
           "ACTION": ""
       },
       {
           "ENCTRID": "116244957",
           "MBRID": "1607132022",
           "MBRLASTNAME": "Oliver",
           "MBRFIRSTNAME": "Kameisha",
           "NPI": "3282556434",
           "PRVDRLASTNAME": "Rubino",
           "PRVDRFIRSTNAME": "Ignazio",
           "FACILITY": "ALL SAINTS...",
           "DOS": "10/02/2016",
           "DOC": "08/10/2016",
           "CREATEDBY": "McCarthy",
           "ENCOUNTERTYPE": "HMO",
           "STATUS": "RESCHEDULED",
           "ACTION": ""
       },
       {
           "ENCTRID": "116244958",
           "MBRID": "1607132022",
           "MBRLASTNAME": "Oliver",
           "MBRFIRSTNAME": "Kameisha",
           "NPI": "3282556434",
           "PRVDRLASTNAME": "Rubino",
           "PRVDRFIRSTNAME": "Ignazio",
           "FACILITY": "ALL SAINTS...",
           "DOS": "08/02/2016",
           "DOC": "08/10/2016",
           "CREATEDBY": "McCarthy",
           "ENCOUNTERTYPE": "MEDICARE",
           "STATUS": "SCHEDULED",
           "ACTION": ""
       },
       {
           "ENCTRID": "116244958",
           "MBRID": "1607132022",
           "MBRLASTNAME": "Oliver",
           "MBRFIRSTNAME": "Kameisha",
           "NPI": "3282556434",
           "PRVDRLASTNAME": "Rubino",
           "PRVDRFIRSTNAME": "Ignazio",
           "FACILITY": "ALL SAINTS...",
           "DOS": "08/02/2016",
           "DOC": "08/10/2016",
           "CREATEDBY": "McCarthy",
           "ENCOUNTERTYPE": "HMO",
           "STATUS": "SCHEDULED",
           "ACTION": ""
       },
       {
           "ENCTRID": "116244960",
           "MBRID": "1607132022",
           "MBRLASTNAME": "Oliver",
           "MBRFIRSTNAME": "Kameisha",
           "NPI": "3282556434",
           "PRVDRLASTNAME": "Rubino",
           "PRVDRFIRSTNAME": "Ignazio",
           "FACILITY": "ALL SAINTS...",
           "DOS": "08/02/2016",
           "DOC": "08/10/2016",
           "CREATEDBY": "McCarthy",
           "ENCOUNTERTYPE": "MEDICARE",
           "STATUS": "SCHEDULED",
           "ACTION": ""
       },
       {
           "ENCTRID": "116244961",
           "MBRID": "1607132022",
           "MBRLASTNAME": "Oliver",
           "MBRFIRSTNAME": "Kameisha",
           "NPI": "3282556434",
           "PRVDRLASTNAME": "Rubino",
           "PRVDRFIRSTNAME": "Ignazio",
           "FACILITY": "ALL SAINTS...",
           "DOS": "08/02/2016",
           "DOC": "08/10/2016",
           "CREATEDBY": "McCarthy",
           "ENCOUNTERTYPE": "HMO",
           "STATUS": "SCHEDULED",
           "ACTION": ""
       },
       {
           "ENCTRID": "116244962",
           "MBRID": "1607132022",
           "MBRLASTNAME": "Oliver",
           "MBRFIRSTNAME": "Kameisha",
           "NPI": "3282556434",
           "PRVDRLASTNAME": "Rubino",
           "PRVDRFIRSTNAME": "Ignazio",
           "FACILITY": "ALL SAINTS...",
           "DOS": "08/02/2016",
           "DOC": "08/10/2016",
           "CREATEDBY": "McCarthy",
           "ENCOUNTERTYPE": "MEDICARE",
           "STATUS": "SCHEDULED",
           "ACTION": ""
       }
    ];
