//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AHC.CD.Entities.DatabaseDesign
{
    using System;
    using System.Collections.Generic;
    
    public partial class BirthInfo
    {
        public int Id { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string BirthCountry { get; set; }
        public string BirthCity { get; set; }
        public string BirthState { get; set; }
        public string BirthCounty { get; set; }
        public string CertificatePath { get; set; }
    }
}
