// <auto-generated />
namespace AHC.CD.Data.EFRepository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class shalabh : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(shalabh));
        
        string IMigrationMetadata.Id
        {
            get { return "201503241051545_shalabh"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
