// <auto-generated />
namespace AHC.CD.Data.EFRepository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class UserID_In_CredRequestTracker_Table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserID_In_CredRequestTracker_Table));
        
        string IMigrationMetadata.Id
        {
            get { return "201704051051003_UserID_In_CredRequestTracker_Table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
