//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AHC.CD.Entities.DatabaseDesign
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactDetails
    {
        public ContactDetails()
        {
            this.PhoneDetails = new HashSet<PhoneDetail>();
            this.EmailDetails = new HashSet<EmailDetail>();
        }
    
        public int Id { get; set; }
        public string PreferredWrittenContact { get; set; }
        public string PreferredContact { get; set; }
        public System.DateTime LastUpdatedOn { get; set; }
    
        public virtual ICollection<PhoneDetail> PhoneDetails { get; set; }
        public virtual ICollection<EmailDetail> EmailDetails { get; set; }
    }
}
