//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AHC.CD.Entities.DatabaseDesign
{
    using System;
    using System.Collections.Generic;
    
    public partial class HospitalPrivilege
    {
        public int Id { get; set; }
        public string StatusExplanation { get; set; }
        public string DepartmentName { get; set; }
        public string DepartmentChief { get; set; }
        public string StaffChief { get; set; }
        public double AnnualAdmittingPercentage { get; set; }
        public bool IsPrivilegeTemporary { get; set; }
        public bool IsPrimary { get; set; }
        public bool IsPrivilegeFullUnrestricted { get; set; }
        public System.DateTime AffiliationStartDate { get; set; }
        public System.DateTime AffiliationEndDate { get; set; }
        public string ExplanationForAffiliationTermination { get; set; }
        public string PrivilegeLetterPath { get; set; }
        public string Status { get; set; }
        public System.DateTime LastUpdatedOn { get; set; }
        public string PreferenceType { get; set; }
    
        public virtual Hospital Hospital { get; set; }
        public virtual HospitalContactInfo HospitalContactInfo { get; set; }
        public virtual HospitalContactPerson HospitalContactPerson { get; set; }
        public virtual StaffCategory StaffCategory { get; set; }
        public virtual AdmittingPrivilege AdmittingPrivilege { get; set; }
        public virtual Specialty Specialty { get; set; }
    }
}
