//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AHC.CD.Entities.DatabaseDesign
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonalDetail
    {
        public PersonalDetail()
        {
            this.ProviderTypes = new HashSet<ProviderType>();
            this.SpouseNames = new HashSet<SpouseName>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Suffix { get; set; }
        public string Gender { get; set; }
        public string MaritalStatus { get; set; }
        public string MaidenName { get; set; }
        public string SpouseName { get; set; }
        public string ImagePath { get; set; }
        public System.DateTime LastUpdatedOn { get; set; }
    
        public virtual ICollection<ProviderType> ProviderTypes { get; set; }
        public virtual ICollection<SpouseName> SpouseNames { get; set; }
    }
}
