//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AHC.CD.Entities.DatabaseDesign
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile
    {
        public Profile()
        {
            this.OtherLegalNames = new HashSet<OtherLegalName>();
            this.HospitalPrivileges = new HashSet<HospitalPrivilege>();
            this.StateLicenses = new HashSet<StateLicense>();
            this.FederalDEAInfoes = new HashSet<FederalDEAInfo>();
            this.MedicareMedicaidInfoes = new HashSet<MedicareMedicaidInfo>();
            this.CDSCInfoes = new HashSet<CDSCInfo>();
            this.HomeAddresses = new HashSet<HomeAddress>();
            this.LanguageInfoes = new HashSet<LanguageInfo>();
            this.ContactDetails = new HashSet<ContactDetails>();
        }
    
        public int Id { get; set; }
        public Nullable<bool> IsCitizenOfUSA { get; set; }
        public System.DateTime LastUpdatedOn { get; set; }
    
        public virtual ICollection<OtherLegalName> OtherLegalNames { get; set; }
        public virtual PersonalDetail PersonalDetail { get; set; }
        public virtual ICollection<HospitalPrivilege> HospitalPrivileges { get; set; }
        public virtual ICollection<StateLicense> StateLicenses { get; set; }
        public virtual ICollection<FederalDEAInfo> FederalDEAInfoes { get; set; }
        public virtual ICollection<MedicareMedicaidInfo> MedicareMedicaidInfoes { get; set; }
        public virtual ICollection<CDSCInfo> CDSCInfoes { get; set; }
        public virtual OtherIdentification OtherIdentifications { get; set; }
        public virtual ICollection<HomeAddress> HomeAddresses { get; set; }
        public virtual PersonalIdentification PersonalIdentifications { get; set; }
        public virtual VisaDetail VisaDetails { get; set; }
        public virtual ICollection<LanguageInfo> LanguageInfoes { get; set; }
        public virtual ICollection<ContactDetails> ContactDetails { get; set; }
        public virtual BirthInfo BirthInfoes { get; set; }
    }
}
