//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AHC.CD.Entities.DatabaseDesign
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisaDetail
    {
        public int Id { get; set; }
        public string VisaNumber { get; set; }
        public string VisaType { get; set; }
        public string VisaStatus { get; set; }
        public string VisaSponsor { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public string CertificatePath { get; set; }
        public string GreenCardNumber { get; set; }
        public string NationalIdNumber { get; set; }
        public string IssuedCountry { get; set; }
        public bool IsAuthorizedToWorkInUs { get; set; }
        public string GreenCardCertificatePath { get; set; }
        public string NationalIdCertificatePath { get; set; }
        public System.DateTime LastUpdatedOn { get; set; }
    }
}
