//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AHC.CD.Entities.DatabaseDesign
{
    using System;
    using System.Collections.Generic;
    
    public partial class OtherIdentification
    {
        public int Id { get; set; }
        public string NPINumber { get; set; }
        public string CAQHNumber { get; set; }
        public string UPINNumber { get; set; }
        public string USMLENumber { get; set; }
        public System.DateTime LastUpdatedOn { get; set; }
    
        public virtual Profile Profile { get; set; }
    }
}
