{
    "State": [
                { Text : "Select", Value : "0" },
                { Text : "ANDAMAN & NIKOBAR ISLANDS", Value : "1" },
                { Text : "ANDHRA PRADESH", Value : "2" },
                { Text : "ARUNACHAL PRADESH", Value : "3" },
                { Text : "ASSAM", Value : "4" },
                { Text : "BIHAR", Value : "5" },
                { Text : "CHANDIGARH", Value : "6" },
                { Text : "CHHATTISGARH", Value : "7" },
                { Text : "DADRA & NAGAR HAVELI", Value : "8" },
                { Text : "DAMAN & DIU", Value : "9" },
                { Text : "GOA", Value : "10" },
                { Text : "GUJARAT", Value : "11" },
                { Text : "HARYANA", Value : "12" },
                { Text : "HIMACHAL PRADESH", Value : "13" },
                { Text : "JAMMU & KASHMIR", Value : "14" },
                { Text : "JHARKHAND", Value : "15" },
                { Text : "KARNATAKA", Value : "16" },
                { Text : "KERALA", Value : "17" },
                { Text : "LAKSHADWEEP", Value : "18" },
                { Text : "MADHYA PRADESH", Value : "19" },
                { Text : "MAHARASHTRA", Value : "20" },
                { Text : "MANIPUR", Value : "21" },
                { Text : "MEGHALAYA", Value : "22" },
                { Text : "MIZORAM", Value : "23" },
                { Text : "NAGALAND", Value : "24" },
                { Text : "NCT OF DELHI", Value : "25" },
                { Text : "ORISSA", Value : "26" },
                { Text : "PUDUCHERRY", Value : "27" },
                { Text : "PUNJAB", Value : "28" },
                { Text : "RAJASTHAN", Value : "29" },
                { Text : "SIKKIM", Value : "30" },
                { Text : "TAMIL NADU", Value : "31" },
                { Text : "TRIPURA", Value : "32" },
                { Text : "UTTAR PRADESH", Value : "33" },
                { Text : "UTTARAKHAND", Value : "34" },
                { Text : "WEST BENGAL", Value : "35" }
       
    ]
}